ALTER TABLE user_profiles
  ADD COLUMN IF NOT EXISTS age_years SMALLINT CHECK (age_years BETWEEN 14 AND 100),
  ADD COLUMN IF NOT EXISTS injuries JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS limitations JSONB NOT NULL DEFAULT '[]'::jsonb;
