INSERT INTO equipment (id, name, category) VALUES
('leg_machine','Тренажёр для ног','machine'),('kettlebell','Гиря','free_weight')
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;

INSERT INTO exercises (id,name,difficulty,movement_pattern,exercise_type,compound,default_sets,rep_min,rep_max,rest_seconds) VALUES
('pullup','Подтягивания','intermediate','vertical_pull','strength',true,4,6,10,120),
('lat_pulldown','Тяга верхнего блока','beginner','vertical_pull','strength',true,3,8,12,90),
('barbell_row','Тяга штанги в наклоне','intermediate','horizontal_pull','strength',true,4,6,10,120),
('dumbbell_row','Тяга гантели одной рукой','beginner','horizontal_pull','strength',true,3,8,12,90),
('seated_cable_row','Горизонтальная тяга блока','beginner','horizontal_pull','strength',true,3,10,12,90),
('chest_supported_row','Тяга гантелей с упором грудью','beginner','horizontal_pull','strength',true,3,8,12,90),
('straight_arm_pulldown','Тяга прямыми руками на блоке','beginner','vertical_pull','strength',false,3,10,15,75),
('cable_face_pull','Face Pull на блоке','beginner','horizontal_pull','strength',false,3,12,20,60),
('band_row','Тяга резины к поясу','beginner','horizontal_pull','strength',true,4,10,15,75),
('band_lat_pulldown','Вертикальная тяга резины','beginner','vertical_pull','strength',true,4,10,15,75),
('band_face_pull','Face Pull с резиной','beginner','horizontal_pull','strength',false,3,12,20,60),
('pushup','Отжимания','beginner','horizontal_push','strength',true,4,8,15,90),
('bench_press','Жим штанги лёжа','intermediate','horizontal_push','strength',true,4,6,10,120),
('incline_dumbbell_press','Жим гантелей под углом','intermediate','horizontal_push','strength',true,3,8,12,90),
('dumbbell_fly','Разведение гантелей лёжа','beginner','horizontal_push','strength',false,3,10,15,75),
('cable_fly','Сведение рук в кроссовере','beginner','horizontal_push','strength',false,3,10,15,75),
('band_chest_press','Жим резины от груди','beginner','horizontal_push','strength',true,4,10,15,75),
('band_fly','Сведение рук с резиной','beginner','horizontal_push','strength',false,3,12,18,60),
('overhead_press','Жим штанги над головой','intermediate','vertical_push','strength',true,4,6,10,120),
('dumbbell_shoulder_press','Жим гантелей сидя','beginner','vertical_push','strength',true,3,8,12,90),
('lateral_raise','Подъём гантелей в стороны','beginner','abduction','strength',false,3,12,18,60),
('cable_lateral_raise','Подъём руки в сторону на блоке','beginner','abduction','strength',false,3,12,18,60),
('band_shoulder_press','Жим резины над головой','beginner','vertical_push','strength',true,4,10,15,75),
('band_lateral_raise','Подъём рук в стороны с резиной','beginner','abduction','strength',false,3,12,20,60),
('barbell_curl','Сгибание рук со штангой','beginner','elbow_flexion','strength',false,3,8,12,75),
('dumbbell_curl','Сгибание рук с гантелями','beginner','elbow_flexion','strength',false,3,8,12,75),
('hammer_curl','Молотковые сгибания','beginner','elbow_flexion','strength',false,3,10,14,75),
('cable_curl','Сгибание рук на нижнем блоке','beginner','elbow_flexion','strength',false,3,10,15,60),
('band_curl','Сгибание рук с резиной','beginner','elbow_flexion','strength',false,4,10,18,60),
('close_grip_pushup','Узкие отжимания','beginner','horizontal_push','strength',true,3,8,15,75),
('close_grip_bench','Жим узким хватом','intermediate','horizontal_push','strength',true,3,6,10,105),
('triceps_pushdown','Разгибание рук на блоке','beginner','elbow_extension','strength',false,3,10,15,60),
('overhead_dumbbell_extension','Разгибание гантели из-за головы','beginner','elbow_extension','strength',false,3,10,15,75),
('band_triceps_pushdown','Разгибание рук с резиной','beginner','elbow_extension','strength',false,4,12,20,60),
('bodyweight_squat','Приседания с собственным весом','beginner','squat','strength',true,4,12,20,90),
('barbell_squat','Приседания со штангой','intermediate','squat','strength',true,4,5,8,150),
('goblet_squat','Гоблет-присед','beginner','squat','strength',true,4,8,12,90),
('split_squat','Болгарские выпады','intermediate','lunge','strength',true,3,8,12,90),
('leg_extension','Разгибание ног в тренажёре','beginner','knee_extension','strength',false,3,10,15,75),
('band_squat','Приседания с резиной','beginner','squat','strength',true,4,10,15,90),
('romanian_deadlift','Румынская тяга','intermediate','hinge','strength',true,4,6,10,120),
('dumbbell_rdl','Румынская тяга с гантелями','beginner','hinge','strength',true,3,8,12,90),
('leg_curl','Сгибание ног в тренажёре','beginner','knee_flexion','strength',false,3,10,15,75),
('band_leg_curl','Сгибание ног с резиной','beginner','knee_flexion','strength',false,4,12,20,60),
('single_leg_rdl','Румынская тяга на одной ноге','intermediate','hinge','strength',true,3,8,12,75),
('hip_thrust','Ягодичный мост со штангой','intermediate','hip_extension','strength',true,4,8,12,105),
('glute_bridge','Ягодичный мост','beginner','hip_extension','strength',true,4,12,20,75),
('dumbbell_hip_thrust','Ягодичный мост с гантелью','beginner','hip_extension','strength',true,4,10,15,90),
('band_glute_bridge','Ягодичный мост с резиной','beginner','hip_extension','strength',true,4,12,20,75),
('band_abduction','Отведение ноги с резиной','beginner','abduction','strength',false,3,15,25,45),
('standing_calf_raise','Подъём на носки стоя','beginner','plantar_flexion','strength',false,4,12,20,60),
('dumbbell_calf_raise','Подъём на носки с гантелями','beginner','plantar_flexion','strength',false,4,10,18,60),
('band_calf_raise','Подъём на носки с резиной','beginner','plantar_flexion','strength',false,4,15,25,60),
('plank','Планка','beginner','anti_extension','strength',false,3,30,60,45),
('dead_bug','Dead Bug','beginner','anti_extension','strength',false,3,8,14,45),
('hanging_knee_raise','Подъём коленей в висе','intermediate','flexion','strength',false,3,8,15,60),
('cable_crunch','Скручивания на верхнем блоке','beginner','flexion','strength',false,3,10,15,60),
('band_pallof_press','Pallof Press с резиной','beginner','anti_rotation','strength',false,3,10,15,45),
('wrist_curl','Сгибание кистей с гантелями','beginner','wrist_flexion','strength',false,3,12,20,45),
('reverse_wrist_curl','Разгибание кистей с гантелями','beginner','wrist_extension','strength',false,3,12,20,45),
('farmer_carry','Фермерская прогулка','beginner','carry','strength',true,4,30,60,60),
('band_wrist_curl','Сгибание кистей с резиной','beginner','wrist_flexion','strength',false,3,15,25,45)
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,difficulty=EXCLUDED.difficulty,movement_pattern=EXCLUDED.movement_pattern,exercise_type=EXCLUDED.exercise_type,compound=EXCLUDED.compound,default_sets=EXCLUDED.default_sets,rep_min=EXCLUDED.rep_min,rep_max=EXCLUDED.rep_max,rest_seconds=EXCLUDED.rest_seconds;

INSERT INTO exercise_muscles (exercise_id,muscle_id,role) VALUES
('pullup','back','primary'),
('pullup','biceps','secondary'),
('lat_pulldown','back','primary'),
('lat_pulldown','biceps','secondary'),
('barbell_row','back','primary'),
('barbell_row','biceps','secondary'),
('barbell_row','core','secondary'),
('dumbbell_row','back','primary'),
('dumbbell_row','biceps','secondary'),
('seated_cable_row','back','primary'),
('seated_cable_row','biceps','secondary'),
('chest_supported_row','back','primary'),
('chest_supported_row','biceps','secondary'),
('straight_arm_pulldown','back','primary'),
('cable_face_pull','back','primary'),
('cable_face_pull','shoulders','secondary'),
('band_row','back','primary'),
('band_row','biceps','secondary'),
('band_lat_pulldown','back','primary'),
('band_lat_pulldown','biceps','secondary'),
('band_face_pull','back','primary'),
('band_face_pull','shoulders','secondary'),
('pushup','chest','primary'),
('pushup','triceps','secondary'),
('pushup','shoulders','secondary'),
('bench_press','chest','primary'),
('bench_press','triceps','secondary'),
('bench_press','shoulders','secondary'),
('incline_dumbbell_press','chest','primary'),
('incline_dumbbell_press','triceps','secondary'),
('incline_dumbbell_press','shoulders','secondary'),
('dumbbell_fly','chest','primary'),
('dumbbell_fly','shoulders','secondary'),
('cable_fly','chest','primary'),
('cable_fly','shoulders','secondary'),
('band_chest_press','chest','primary'),
('band_chest_press','triceps','secondary'),
('band_chest_press','shoulders','secondary'),
('band_fly','chest','primary'),
('band_fly','shoulders','secondary'),
('overhead_press','shoulders','primary'),
('overhead_press','triceps','secondary'),
('dumbbell_shoulder_press','shoulders','primary'),
('dumbbell_shoulder_press','triceps','secondary'),
('lateral_raise','shoulders','primary'),
('cable_lateral_raise','shoulders','primary'),
('band_shoulder_press','shoulders','primary'),
('band_shoulder_press','triceps','secondary'),
('band_lateral_raise','shoulders','primary'),
('barbell_curl','biceps','primary'),
('barbell_curl','forearms','secondary'),
('dumbbell_curl','biceps','primary'),
('dumbbell_curl','forearms','secondary'),
('hammer_curl','biceps','primary'),
('hammer_curl','forearms','secondary'),
('cable_curl','biceps','primary'),
('cable_curl','forearms','secondary'),
('band_curl','biceps','primary'),
('band_curl','forearms','secondary'),
('close_grip_pushup','triceps','primary'),
('close_grip_pushup','chest','secondary'),
('close_grip_bench','triceps','primary'),
('close_grip_bench','chest','secondary'),
('triceps_pushdown','triceps','primary'),
('overhead_dumbbell_extension','triceps','primary'),
('band_triceps_pushdown','triceps','primary'),
('bodyweight_squat','quads','primary'),
('bodyweight_squat','glutes','secondary'),
('bodyweight_squat','core','secondary'),
('barbell_squat','quads','primary'),
('barbell_squat','glutes','secondary'),
('barbell_squat','hamstrings','secondary'),
('barbell_squat','core','secondary'),
('goblet_squat','quads','primary'),
('goblet_squat','glutes','secondary'),
('goblet_squat','core','secondary'),
('split_squat','quads','primary'),
('split_squat','glutes','secondary'),
('leg_extension','quads','primary'),
('band_squat','quads','primary'),
('band_squat','glutes','secondary'),
('romanian_deadlift','hamstrings','primary'),
('romanian_deadlift','glutes','secondary'),
('romanian_deadlift','back','secondary'),
('dumbbell_rdl','hamstrings','primary'),
('dumbbell_rdl','glutes','secondary'),
('leg_curl','hamstrings','primary'),
('band_leg_curl','hamstrings','primary'),
('single_leg_rdl','hamstrings','primary'),
('single_leg_rdl','glutes','secondary'),
('single_leg_rdl','core','secondary'),
('hip_thrust','glutes','primary'),
('hip_thrust','hamstrings','secondary'),
('glute_bridge','glutes','primary'),
('glute_bridge','hamstrings','secondary'),
('dumbbell_hip_thrust','glutes','primary'),
('dumbbell_hip_thrust','hamstrings','secondary'),
('band_glute_bridge','glutes','primary'),
('band_glute_bridge','hamstrings','secondary'),
('band_abduction','glutes','primary'),
('standing_calf_raise','calves','primary'),
('dumbbell_calf_raise','calves','primary'),
('band_calf_raise','calves','primary'),
('plank','core','primary'),
('dead_bug','core','primary'),
('hanging_knee_raise','core','primary'),
('hanging_knee_raise','forearms','secondary'),
('cable_crunch','core','primary'),
('band_pallof_press','core','primary'),
('wrist_curl','forearms','primary'),
('reverse_wrist_curl','forearms','primary'),
('farmer_carry','forearms','primary'),
('farmer_carry','core','secondary'),
('farmer_carry','shoulders','secondary'),
('band_wrist_curl','forearms','primary')
ON CONFLICT DO NOTHING;

INSERT INTO exercise_environments (exercise_id,environment) VALUES
('pullup','gym'),
('pullup','home'),
('lat_pulldown','gym'),
('barbell_row','gym'),
('dumbbell_row','gym'),
('dumbbell_row','home'),
('seated_cable_row','gym'),
('chest_supported_row','gym'),
('straight_arm_pulldown','gym'),
('cable_face_pull','gym'),
('band_row','band'),
('band_row','home'),
('band_lat_pulldown','band'),
('band_lat_pulldown','home'),
('band_face_pull','band'),
('band_face_pull','home'),
('pushup','home'),
('pushup','gym'),
('bench_press','gym'),
('incline_dumbbell_press','gym'),
('incline_dumbbell_press','home'),
('dumbbell_fly','gym'),
('dumbbell_fly','home'),
('cable_fly','gym'),
('band_chest_press','band'),
('band_chest_press','home'),
('band_fly','band'),
('band_fly','home'),
('overhead_press','gym'),
('dumbbell_shoulder_press','gym'),
('dumbbell_shoulder_press','home'),
('lateral_raise','gym'),
('lateral_raise','home'),
('cable_lateral_raise','gym'),
('band_shoulder_press','band'),
('band_shoulder_press','home'),
('band_lateral_raise','band'),
('band_lateral_raise','home'),
('barbell_curl','gym'),
('dumbbell_curl','gym'),
('dumbbell_curl','home'),
('hammer_curl','gym'),
('hammer_curl','home'),
('cable_curl','gym'),
('band_curl','band'),
('band_curl','home'),
('close_grip_pushup','home'),
('close_grip_pushup','gym'),
('close_grip_bench','gym'),
('triceps_pushdown','gym'),
('overhead_dumbbell_extension','gym'),
('overhead_dumbbell_extension','home'),
('band_triceps_pushdown','band'),
('band_triceps_pushdown','home'),
('bodyweight_squat','home'),
('bodyweight_squat','gym'),
('barbell_squat','gym'),
('goblet_squat','gym'),
('goblet_squat','home'),
('split_squat','gym'),
('split_squat','home'),
('leg_extension','gym'),
('band_squat','band'),
('band_squat','home'),
('romanian_deadlift','gym'),
('dumbbell_rdl','gym'),
('dumbbell_rdl','home'),
('leg_curl','gym'),
('band_leg_curl','band'),
('band_leg_curl','home'),
('single_leg_rdl','home'),
('single_leg_rdl','gym'),
('hip_thrust','gym'),
('glute_bridge','home'),
('glute_bridge','gym'),
('dumbbell_hip_thrust','home'),
('dumbbell_hip_thrust','gym'),
('band_glute_bridge','band'),
('band_glute_bridge','home'),
('band_abduction','band'),
('band_abduction','home'),
('standing_calf_raise','home'),
('standing_calf_raise','gym'),
('dumbbell_calf_raise','home'),
('dumbbell_calf_raise','gym'),
('band_calf_raise','band'),
('band_calf_raise','home'),
('plank','home'),
('plank','gym'),
('dead_bug','home'),
('dead_bug','gym'),
('hanging_knee_raise','gym'),
('hanging_knee_raise','home'),
('cable_crunch','gym'),
('band_pallof_press','band'),
('band_pallof_press','home'),
('wrist_curl','home'),
('wrist_curl','gym'),
('reverse_wrist_curl','home'),
('reverse_wrist_curl','gym'),
('farmer_carry','gym'),
('farmer_carry','home'),
('band_wrist_curl','band'),
('band_wrist_curl','home')
ON CONFLICT DO NOTHING;

INSERT INTO exercise_equipment (exercise_id,equipment_id) VALUES
('pullup','pullup_bar'),
('lat_pulldown','cable_machine'),
('barbell_row','barbell'),
('dumbbell_row','dumbbells'),
('seated_cable_row','cable_machine'),
('chest_supported_row','dumbbells'),
('chest_supported_row','bench'),
('straight_arm_pulldown','cable_machine'),
('cable_face_pull','cable_machine'),
('band_row','resistance_band'),
('band_lat_pulldown','resistance_band'),
('band_face_pull','resistance_band'),
('pushup','bodyweight'),
('bench_press','barbell'),
('bench_press','bench'),
('incline_dumbbell_press','dumbbells'),
('incline_dumbbell_press','bench'),
('dumbbell_fly','dumbbells'),
('dumbbell_fly','bench'),
('cable_fly','cable_machine'),
('band_chest_press','resistance_band'),
('band_fly','resistance_band'),
('overhead_press','barbell'),
('dumbbell_shoulder_press','dumbbells'),
('lateral_raise','dumbbells'),
('cable_lateral_raise','cable_machine'),
('band_shoulder_press','resistance_band'),
('band_lateral_raise','resistance_band'),
('barbell_curl','barbell'),
('dumbbell_curl','dumbbells'),
('hammer_curl','dumbbells'),
('cable_curl','cable_machine'),
('band_curl','resistance_band'),
('close_grip_pushup','bodyweight'),
('close_grip_bench','barbell'),
('close_grip_bench','bench'),
('triceps_pushdown','cable_machine'),
('overhead_dumbbell_extension','dumbbells'),
('band_triceps_pushdown','resistance_band'),
('bodyweight_squat','bodyweight'),
('barbell_squat','barbell'),
('barbell_squat','rack'),
('goblet_squat','dumbbells'),
('split_squat','dumbbells'),
('leg_extension','leg_machine'),
('band_squat','resistance_band'),
('romanian_deadlift','barbell'),
('dumbbell_rdl','dumbbells'),
('leg_curl','leg_machine'),
('band_leg_curl','resistance_band'),
('single_leg_rdl','dumbbells'),
('hip_thrust','barbell'),
('hip_thrust','bench'),
('glute_bridge','bodyweight'),
('dumbbell_hip_thrust','dumbbells'),
('dumbbell_hip_thrust','bench'),
('band_glute_bridge','resistance_band'),
('band_abduction','resistance_band'),
('standing_calf_raise','bodyweight'),
('dumbbell_calf_raise','dumbbells'),
('band_calf_raise','resistance_band'),
('plank','bodyweight'),
('dead_bug','bodyweight'),
('hanging_knee_raise','pullup_bar'),
('cable_crunch','cable_machine'),
('band_pallof_press','resistance_band'),
('wrist_curl','dumbbells'),
('reverse_wrist_curl','dumbbells'),
('farmer_carry','dumbbells'),
('band_wrist_curl','resistance_band')
ON CONFLICT DO NOTHING;
