import React, {useState} from 'react';
import {Pressable, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {api, AIFoodDraft, FoodEntry} from '../api/client';
import {AIFoodDraftView} from '../components/AIFoodDraftView';
import {AppButton} from '../components/AppButton';
import {colors, control, radius, spacing} from '../theme/tokens';

export function AIFoodInputScreen({accessToken,onBack,onPhoto,onDone}:{accessToken:string;onBack:()=>void;onPhoto:()=>void;onDone:()=>void}) {
  const [text,setText]=useState('');const[draft,setDraft]=useState<AIFoodDraft|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  const trimmed=text.trim();
  async function parse(){if(!trimmed||busy)return;try{setBusy(true);setError('');setDraft(await api.aiParseFoodText(accessToken,trimmed));}catch(e){setError(e instanceof Error?e.message:'Не удалось распознать еду');}finally{setBusy(false)}}
  async function confirm(meal:FoodEntry['meal_type'],items:Array<{food_id:string;quantity_g:number}>){try{setBusy(true);setError('');await api.aiConfirmFood(accessToken,meal,items);onDone();}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить');}finally{setBusy(false)}}
  return <ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled"><Pressable accessibilityRole="button" accessibilityLabel="Вернуться к питанию" hitSlop={8} onPress={onBack} style={styles.navButton}><Text style={styles.back}>← Питание</Text></Pressable><Text style={styles.kicker}>AI FOOD INPUT</Text><Text accessibilityRole="header" style={styles.title}>Расскажите, что съели</Text><Text style={styles.subtitle}>Добавьте продукты и примерный вес: «200 г творога, банан и 30 г протеина». Каталог приложения рассчитает калории и БЖУ.</Text><View style={styles.info}><Text style={styles.infoTitle}>Вы подтверждаете результат</Text><Text style={styles.infoText}>AI может ошибиться в продукте или порции. До подтверждения запись не попадёт в дневник.</Text></View><TextInput accessibilityLabel="Описание еды" multiline value={text} onChangeText={value=>{setText(value);if(error)setError('')}} maxLength={1000} placeholder="Например: омлет из 3 яиц и два тоста" placeholderTextColor={colors.textMuted} style={styles.textarea}/><Text style={styles.counter}>{text.length}/1000</Text><AppButton label="Разобрать текст" loading={busy&&!draft} disabled={busy||!trimmed} onPress={()=>void parse()}/><AppButton label="Добавить по фотографии" variant="secondary" disabled={busy} onPress={onPhoto}/>{draft?<><Text style={styles.section}>Проверьте распознавание</Text><AIFoodDraftView draft={draft} onConfirm={(meal,items)=>void confirm(meal,items)} busy={busy}/></>:null}{error?<View style={styles.errorBox}><Text accessibilityRole="alert" style={styles.error}>{error}</Text><AppButton label="Повторить" variant="secondary" disabled={busy||!trimmed} onPress={()=>void parse()}/></View>:null}</ScrollView>;
}
const styles=StyleSheet.create({container:{padding:spacing.lg,gap:spacing.sm,backgroundColor:colors.background},navButton:{minHeight:control.minTouch,justifyContent:'center',alignSelf:'flex-start'},back:{fontWeight:'800',color:colors.text},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.4,color:colors.textMuted},title:{fontSize:30,fontWeight:'900',color:colors.text},subtitle:{fontSize:14,lineHeight:20,color:colors.textMuted},info:{backgroundColor:colors.surfaceMuted,borderRadius:radius.md,padding:spacing.md,gap:spacing.xs,marginVertical:spacing.xs},infoTitle:{fontWeight:'900',color:colors.text},infoText:{fontSize:12,lineHeight:18,color:colors.textMuted},textarea:{minHeight:120,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,textAlignVertical:'top',fontSize:16,color:colors.text,backgroundColor:colors.surface},counter:{fontSize:11,color:colors.textMuted,textAlign:'right'},section:{fontSize:18,fontWeight:'900',color:colors.text,marginTop:spacing.sm},errorBox:{borderWidth:1,borderColor:colors.danger,borderRadius:radius.md,padding:spacing.md,gap:spacing.sm},error:{fontSize:12,lineHeight:18,fontWeight:'700',color:colors.danger}});
