import React, {useState} from 'react';
import {Pressable, ScrollView, StyleSheet, Text, TextInput} from 'react-native';
import {api, AIFoodDraft, FoodEntry} from '../api/client';
import {AIFoodDraftView} from '../components/AIFoodDraftView';

export function AIFoodInputScreen({accessToken,onBack,onPhoto,onDone}:{accessToken:string;onBack:()=>void;onPhoto:()=>void;onDone:()=>void}) {
  const [text,setText]=useState('');const[draft,setDraft]=useState<AIFoodDraft|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  async function parse(){if(!text.trim())return;try{setBusy(true);setError('');setDraft(await api.aiParseFoodText(accessToken,text));}catch(e){setError(e instanceof Error?e.message:'Не удалось распознать еду');}finally{setBusy(false)}}
  async function confirm(meal:FoodEntry['meal_type'],items:Array<{food_id:string;quantity_g:number}>){try{setBusy(true);setError('');await api.aiConfirmFood(accessToken,meal,items);onDone();}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить');}finally{setBusy(false)}}
  return <ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled"><Pressable onPress={onBack}><Text style={styles.back}>← Питание</Text></Pressable><Text style={styles.kicker}>AI FOOD INPUT</Text><Text style={styles.title}>Расскажи, что съел</Text><Text style={styles.subtitle}>Например: «200 г творога, банан и 30 г протеина». AI извлечёт продукты, а калории и БЖУ посчитает каталог приложения.</Text><TextInput multiline value={text} onChangeText={setText} placeholder="Съел…" style={styles.textarea}/><Pressable onPress={()=>void parse()} disabled={busy} style={styles.primary}><Text style={styles.primaryText}>{busy?'Разбираю…':'Разобрать текст'}</Text></Pressable><Pressable onPress={onPhoto} style={styles.secondary}><Text style={styles.secondaryText}>📷 Добавить по фотографии</Text></Pressable>{draft?<AIFoodDraftView draft={draft} onConfirm={(meal,items)=>void confirm(meal,items)} busy={busy}/>:null}{error?<Text style={styles.error}>{error}</Text>:null}</ScrollView>;
}
const styles=StyleSheet.create({container:{padding:20,gap:13},back:{fontWeight:'850'},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.4,opacity:.5},title:{fontSize:30,fontWeight:'950'},subtitle:{fontSize:14,lineHeight:20,opacity:.6},textarea:{minHeight:110,borderWidth:1,borderRadius:18,padding:14,textAlignVertical:'top',fontSize:16},primary:{backgroundColor:'#111',borderRadius:16,padding:15,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'900'},secondary:{borderWidth:1,borderRadius:16,padding:14,alignItems:'center'},secondaryText:{fontWeight:'900'},error:{fontSize:12,fontWeight:'750'}});
