import React, {useCallback, useEffect, useState} from 'react';
import {ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {api, ProfileResponse} from '../api/client';
import {AppButton} from '../components/AppButton';
import {colors, control, radius, spacing} from '../theme/tokens';

const goals = [['muscle_gain','Набор мышц'],['fat_loss','Снижение веса'],['recomposition','Рекомпозиция'],['strength','Сила'],['endurance','Выносливость'],['maintenance','Здоровье']] as const;
const levels = [['beginner','Новичок'],['intermediate','Средний'],['advanced','Продвинутый']] as const;
const places = [['gym','Зал'],['home','Дом'],['band','Резинки']] as const;
const gear = [['bodyweight','Собственный вес'],['dumbbells','Гантели'],['barbell','Штанга'],['bench','Скамья'],['rack','Стойка'],['pullup_bar','Турник'],['cable_machine','Блочный тренажёр'],['leg_machine','Тренажёры для ног'],['resistance_band','Резинки'],['kettlebell','Гиря']] as const;

type Form = {height:string;weight:string;age:string;goal:string;level:string;environments:string[];equipment:string[];workouts:number;minutes:number;injuries:string;limitations:string};
const empty: Form = {height:'',weight:'',age:'',goal:'maintenance',level:'beginner',environments:['gym'],equipment:['bodyweight'],workouts:3,minutes:60,injuries:'',limitations:''};
const lines=(value:string)=>value.split('\n').map(x=>x.trim()).filter(Boolean);
const number=(value:string)=>Number(value.replace(',','.'));

export function AthleteProfileScreen({accessToken,onBack,onLogout}:{accessToken:string;onBack:()=>void;onLogout:()=>void}) {
  const [form,setForm]=useState<Form>(empty); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [saved,setSaved]=useState(false);
  const load=useCallback(async()=>{try{setLoading(true);setError('');const data=await api.getProfile(accessToken);setForm(fromProfile(data));}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить профиль.')}finally{setLoading(false)}},[accessToken]);
  useEffect(()=>{void load()},[load]);
  const height=number(form.height),weight=number(form.weight),age=Number(form.age);
  const validation=!Number.isFinite(height)||height<100||height>250?'Рост должен быть от 100 до 250 см.':!Number.isFinite(weight)||weight<30||weight>400?'Вес должен быть от 30 до 400 кг.':!Number.isInteger(age)||age<14||age>100?'Возраст должен быть от 14 до 100 лет.':form.environments.length===0?'Выберите хотя бы одно место тренировки.':form.equipment.length===0?'Выберите хотя бы один вариант оборудования.':lines(form.injuries).some(x=>x.length>120)||lines(form.limitations).some(x=>x.length>120)?'Каждое ограничение — не более 120 символов.':'';
  const patch=(value:Partial<Form>)=>{setForm(current=>({...current,...value}));setSaved(false);setError('')};
  const toggle=(key:'environments'|'equipment',value:string)=>patch({[key]:form[key].includes(value)?form[key].filter(x=>x!==value):[...form[key],value]} as Partial<Form>);
  async function save(){if(validation||saving)return;try{setSaving(true);setError('');await api.updateProfile(accessToken,{height_cm:height,weight_kg:weight,age_years:age,experience_level:form.level,injuries:lines(form.injuries),limitations:lines(form.limitations),unit_system:'metric'});await api.setGoal(accessToken,form.goal);await api.setTrainingPreferences(accessToken,{environments:form.environments,equipment_ids:form.equipment,workouts_per_week:form.workouts,session_minutes:form.minutes});setSaved(true);}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить профиль. Изменения можно повторить.')}finally{setSaving(false)}}
  if(loading)return <View style={styles.center} accessibilityRole="progressbar"><ActivityIndicator/><Text style={styles.muted}>Загружаем профиль…</Text></View>;
  if(error&&!form.height)return <View style={styles.center}><Text accessibilityRole="alert" style={styles.error}>{error}</Text><AppButton label="Повторить" onPress={()=>void load()}/><AppButton label="Назад" variant="secondary" onPress={onBack}/></View>;
  return <ScrollView testID="athlete-profile-screen" keyboardShouldPersistTaps="handled" contentContainerStyle={styles.container}>
    <Pressable accessibilityRole="button" onPress={onBack} style={styles.back}><Text style={styles.backText}>← Назад</Text></Pressable><Text style={styles.kicker}>ПРОФИЛЬ СПОРТСМЕНА</Text><Text accessibilityRole="header" style={styles.title}>Настрой тренировки под себя</Text><Text style={styles.muted}>Эти данные управляют подбором нагрузки. Травмы не заменяют консультацию врача.</Text>
    <Text style={styles.section}>Параметры</Text><View style={styles.row}>{input('Рост, см',form.height,v=>patch({height:v}),'number-pad')}{input('Вес, кг',form.weight,v=>patch({weight:v}),'decimal-pad')}{input('Возраст',form.age,v=>patch({age:v}),'number-pad')}</View>
    <Choice title="Цель" items={goals} selected={[form.goal]} onPress={value=>patch({goal:value})}/><Choice title="Опыт" items={levels} selected={[form.level]} onPress={value=>patch({level:value})}/><Choice title="Место тренировок" items={places} selected={form.environments} onPress={value=>toggle('environments',value)} multi/><Choice title="Оборудование" items={gear} selected={form.equipment} onPress={value=>toggle('equipment',value)} multi/>
    <Text style={styles.section}>Режим</Text><Stepper label="Тренировок в неделю" value={form.workouts} min={1} max={14} onChange={value=>patch({workouts:value})}/><Stepper label="Продолжительность, минут" value={form.minutes} min={10} max={180} step={5} onChange={value=>patch({minutes:value})}/>
    <Text style={styles.section}>Травмы и ограничения</Text><Text style={styles.muted}>Каждый пункт вводите с новой строки. Это влияет на безопасные замены упражнений.</Text><TextInput accessibilityLabel="Травмы" placeholder="Например: операция на правом плече" placeholderTextColor={colors.textMuted} multiline maxLength={1000} value={form.injuries} onChangeText={v=>patch({injuries:v})} style={styles.notes}/><TextInput accessibilityLabel="Ограничения" placeholder="Например: исключить болезненные разведения рук" placeholderTextColor={colors.textMuted} multiline maxLength={1000} value={form.limitations} onChangeText={v=>patch({limitations:v})} style={styles.notes}/>
    {validation?<Text accessibilityRole="alert" style={styles.error}>{validation}</Text>:null}{error?<Text accessibilityRole="alert" style={styles.error}>{error}</Text>:null}{saved?<Text accessibilityLiveRegion="polite" style={styles.success}>Профиль сохранён.</Text>:null}<AppButton testID="athlete-profile-save" label="Сохранить профиль" loading={saving} disabled={!!validation} onPress={()=>void save()}/><AppButton label="Выйти из аккаунта" variant="secondary" onPress={onLogout}/>
  </ScrollView>;
}

function fromProfile(data:ProfileResponse):Form {const p=data.profile,t=data.training_preferences;return {...empty,height:p.height_cm?.toString()??'',weight:p.weight_kg?.toString()??'',age:p.age_years?.toString()??'',level:p.experience_level??'beginner',goal:data.goal?.goal_type??'maintenance',environments:t?.environments??['gym'],equipment:t?.equipment_ids??['bodyweight'],workouts:t?.workouts_per_week??3,minutes:t?.session_minutes??60,injuries:(p.injuries??[]).join('\n'),limitations:(p.limitations??[]).join('\n')}}
function input(label:string,value:string,onChange:(v:string)=>void,keyboard:'number-pad'|'decimal-pad'){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} keyboardType={keyboard} style={styles.input}/></View>}
function Choice({title,items,selected,onPress,multi=false}:{title:string;items:readonly (readonly [string,string])[];selected:string[];onPress:(v:string)=>void;multi?:boolean}){return <View><Text style={styles.section}>{title}</Text><View style={styles.chips}>{items.map(([id,label])=><Pressable key={id} accessibilityRole={multi?'checkbox':'radio'} accessibilityState={{checked:multi?selected.includes(id):undefined,selected:!multi?selected.includes(id):undefined}} onPress={()=>onPress(id)} style={[styles.chip,selected.includes(id)&&styles.chipOn]}><Text style={[styles.chipText,selected.includes(id)&&styles.chipTextOn]}>{label}</Text></Pressable>)}</View></View>}
function Stepper({label,value,min,max,step=1,onChange}:{label:string;value:number;min:number;max:number;step?:number;onChange:(v:number)=>void}){return <View style={styles.stepper}><Text style={styles.label}>{label}</Text><View style={styles.stepActions}><Pressable accessibilityRole="button" accessibilityLabel={`Уменьшить ${label}`} disabled={value<=min} onPress={()=>onChange(value-step)} style={styles.circle}><Text>−</Text></Pressable><Text style={styles.value}>{value}</Text><Pressable accessibilityRole="button" accessibilityLabel={`Увеличить ${label}`} disabled={value>=max} onPress={()=>onChange(value+step)} style={styles.circle}><Text>+</Text></Pressable></View></View>}
const styles=StyleSheet.create({container:{padding:spacing.lg,paddingBottom:spacing.xl,gap:spacing.md,backgroundColor:colors.background},center:{flex:1,padding:spacing.xl,alignItems:'center',justifyContent:'center',gap:spacing.md},back:{minHeight:control.minTouch,justifyContent:'center',alignSelf:'flex-start'},backText:{fontWeight:'800',color:colors.text},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.3,color:colors.textMuted},title:{fontSize:30,lineHeight:36,fontWeight:'900',color:colors.text},muted:{fontSize:13,lineHeight:19,color:colors.textMuted},section:{fontSize:18,fontWeight:'900',color:colors.text,marginTop:spacing.sm},row:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},field:{flexGrow:1,minWidth:95,gap:5},label:{fontSize:13,fontWeight:'800',color:colors.text},input:{minHeight:control.minTouch,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:12,color:colors.text,backgroundColor:colors.surface},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{minHeight:control.minTouch,borderWidth:1,borderColor:colors.border,borderRadius:radius.pill,paddingHorizontal:14,alignItems:'center',justifyContent:'center'},chipOn:{backgroundColor:colors.primary,borderColor:colors.primary},chipText:{fontWeight:'800',color:colors.text},chipTextOn:{color:colors.inverse},stepper:{borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},stepActions:{flexDirection:'row',alignItems:'center',gap:10},circle:{width:control.minTouch,height:control.minTouch,borderWidth:1,borderColor:colors.border,borderRadius:radius.pill,alignItems:'center',justifyContent:'center'},value:{minWidth:34,textAlign:'center',fontSize:18,fontWeight:'900',color:colors.text},notes:{minHeight:92,textAlignVertical:'top',borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:12,color:colors.text,backgroundColor:colors.surface},error:{color:colors.danger,fontWeight:'700'},success:{color:colors.success,fontWeight:'800'}});
