import React, {useEffect, useMemo, useState} from 'react';
import {Pressable, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {api, FoodEntry, FoodItem, NutritionDay} from '../api/client';

const meals: Array<{id: FoodEntry['meal_type']; title: string}> = [
  {id: 'breakfast', title: 'Завтрак'}, {id: 'lunch', title: 'Обед'}, {id: 'dinner', title: 'Ужин'}, {id: 'snack', title: 'Перекус'},
];

export function FoodSearchScreen({accessToken,onBack,onLogged,onCustom,onRecipes}:{accessToken:string;onBack:()=>void;onLogged:(day:NutritionDay)=>void;onCustom:()=>void;onRecipes:()=>void}) {
  const [query,setQuery]=useState(''); const [barcode,setBarcode]=useState(''); const [items,setItems]=useState<FoodItem[]>([]); const [selected,setSelected]=useState<FoodItem|null>(null); const [meal,setMeal]=useState<FoodEntry['meal_type']>('lunch'); const [grams,setGrams]=useState('200'); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  useEffect(()=>{void search('')},[]);
  async function search(value=query){try{setLoading(true);setError('');setItems((await api.searchFoods(accessToken,value)).items)}catch(e){setError(e instanceof Error?e.message:'Ошибка поиска')}finally{setLoading(false)}}
  async function lookupBarcode(){if(!barcode.trim())return;try{setError('');const food=await api.foodByBarcode(accessToken,barcode.trim());setSelected(food);setItems([food]);setGrams(String(Math.round(food.serving_g||100)))}catch(e){setError(e instanceof Error?e.message:'Штрихкод не найден')}}
  const preview=useMemo(()=>{if(!selected)return null;const amount=Number(grams.replace(',','.'))||0;const factor=amount/100;return{kcal:Math.round(selected.kcal_per_100g*factor),p:Math.round(selected.protein_per_100g*factor),f:Math.round(selected.fat_per_100g*factor),c:Math.round(selected.carbs_per_100g*factor)}},[selected,grams]);
  async function add(){if(!selected)return;const amount=Number(grams.replace(',','.'));if(!Number.isFinite(amount)||amount<=0){setError('Укажи корректную граммовку');return}try{setError('');onLogged(await api.logFood(accessToken,{food_id:selected.id,meal_type:meal,quantity_g:amount}))}catch(e){setError(e instanceof Error?e.message:'Не удалось добавить продукт')}}
  return <ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">
    <View style={styles.header}><Pressable onPress={onBack}><Text style={styles.back}>← Назад</Text></Pressable><Text style={styles.kicker}>ДОБАВИТЬ ЕДУ</Text></View><Text style={styles.title}>Что съел?</Text>
    <View style={styles.actions}><Pressable onPress={onCustom} style={styles.action}><Text style={styles.actionText}>＋ Свой продукт</Text></Pressable><Pressable onPress={onRecipes} style={styles.action}><Text style={styles.actionText}>Рецепты</Text></Pressable></View>
    <View style={styles.searchRow}><TextInput value={query} onChangeText={setQuery} onSubmitEditing={()=>void search()} placeholder="Творог, рис, курица…" style={styles.input}/><Pressable onPress={()=>void search()} style={styles.searchBtn}><Text style={styles.searchBtnText}>Найти</Text></Pressable></View>
    <View style={styles.searchRow}><TextInput value={barcode} onChangeText={setBarcode} onSubmitEditing={()=>void lookupBarcode()} keyboardType="number-pad" placeholder="Штрихкод" style={styles.input}/><Pressable onPress={()=>void lookupBarcode()} style={styles.secondary}><Text style={styles.secondaryText}>Проверить</Text></Pressable></View>
    <View style={styles.meals}>{meals.map(x=><Pressable key={x.id} onPress={()=>setMeal(x.id)} style={[styles.meal,meal===x.id&&styles.mealActive]}><Text style={[styles.mealText,meal===x.id&&styles.white]}>{x.title}</Text></Pressable>)}</View>
    {loading?<Text style={styles.muted}>Ищу…</Text>:null}<View style={styles.list}>{items.map(item=><Pressable key={item.id} onPress={()=>{setSelected(item);setGrams(String(Math.round(item.serving_g||100)))}} style={[styles.food,selected?.id===item.id&&styles.foodSelected]}><View style={{flex:1}}><Text style={[styles.foodTitle,selected?.id===item.id&&styles.white]}>{item.name}</Text><Text style={[styles.foodMeta,selected?.id===item.id&&styles.whiteSoft]}>{item.source==='custom'?'Мой продукт · ':''}{Math.round(item.kcal_per_100g)} kcal · Б {item.protein_per_100g} · Ж {item.fat_per_100g} · У {item.carbs_per_100g} / 100 г</Text></View></Pressable>)}</View>
    {selected?<View style={styles.editor}><Text style={styles.editorTitle}>{selected.name}</Text><Text style={styles.label}>Количество, г</Text><TextInput value={grams} onChangeText={setGrams} keyboardType="decimal-pad" style={styles.grams}/><Text style={styles.preview}>{preview?.kcal??0} kcal · Б {preview?.p??0} · Ж {preview?.f??0} · У {preview?.c??0}</Text><Pressable onPress={()=>void add()} style={styles.primary}><Text style={styles.primaryText}>Добавить в дневник</Text></Pressable></View>:null}{error?<Text style={styles.error}>{error}</Text>:null}
  </ScrollView>
}
const styles=StyleSheet.create({container:{padding:20,gap:14},header:{flexDirection:'row',justifyContent:'space-between'},back:{fontWeight:'800'},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.3,opacity:.55},title:{fontSize:30,fontWeight:'900'},actions:{flexDirection:'row',gap:8},action:{flex:1,borderWidth:1,borderRadius:14,paddingVertical:11,alignItems:'center'},actionText:{fontWeight:'850',fontSize:12},searchRow:{flexDirection:'row',gap:8},input:{flex:1,borderWidth:1,borderRadius:14,paddingHorizontal:13,paddingVertical:11,fontSize:15},searchBtn:{backgroundColor:'#111',borderRadius:14,paddingHorizontal:16,justifyContent:'center'},searchBtnText:{color:'#fff',fontWeight:'850'},secondary:{borderWidth:1,borderRadius:14,paddingHorizontal:14,justifyContent:'center'},secondaryText:{fontWeight:'850'},meals:{flexDirection:'row',flexWrap:'wrap',gap:7},meal:{borderWidth:1,borderRadius:999,paddingHorizontal:12,paddingVertical:8},mealActive:{backgroundColor:'#111'},mealText:{fontSize:12,fontWeight:'750'},white:{color:'#fff'},whiteSoft:{color:'#fff',opacity:.72},muted:{opacity:.5},list:{gap:8},food:{borderWidth:1,borderRadius:16,padding:13,flexDirection:'row'},foodSelected:{backgroundColor:'#111'},foodTitle:{fontSize:15,fontWeight:'850'},foodMeta:{fontSize:11,lineHeight:16,opacity:.58,marginTop:4},editor:{borderWidth:1,borderRadius:20,padding:16,gap:9,marginTop:5},editorTitle:{fontSize:18,fontWeight:'900'},label:{fontSize:12,fontWeight:'750',opacity:.6},grams:{borderWidth:1,borderRadius:12,paddingHorizontal:12,paddingVertical:10,fontSize:18,fontWeight:'800'},preview:{fontWeight:'800'},primary:{backgroundColor:'#111',borderRadius:15,paddingVertical:14,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'900'},error:{fontSize:13,fontWeight:'700'}});
