import React, {useEffect, useMemo, useState} from 'react';
import {ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {api, Exercise, ManualWorkoutExerciseInput, WorkoutView} from '../api/client';
import {muscleIds, muscleMeta} from '../domain/muscles';
import {AppButton} from '../components/AppButton';
import {colors, control, radius, spacing} from '../theme/tokens';

type Environment='home'|'gym'|'band';
type Draft=ManualWorkoutExerciseInput;
const environmentOptions:Array<[Environment,string]>=[['gym','Зал'],['home','Дом'],['band','Резина']];

export function ManualWorkoutScreen({accessToken,onBack,onCreated}:{accessToken:string;onBack:()=>void;onCreated:(workout:WorkoutView)=>void}) {
  const [environment,setEnvironment]=useState<Environment>('gym');
  const [allowedEnvironments,setAllowedEnvironments]=useState<Environment[]>(['gym']);
  const [muscle,setMuscle]=useState('chest');
  const [duration,setDuration]=useState('45');
  const [query,setQuery]=useState('');
  const [catalog,setCatalog]=useState<Exercise[]>([]);
  const [drafts,setDrafts]=useState<Record<string,Draft>>({});
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');

  useEffect(()=>{api.getProfile(accessToken).then(profile=>{const allowed=profile.training_preferences?.environments??[];if(allowed.length){setAllowedEnvironments(allowed);setEnvironment(current=>allowed.includes(current)?current:allowed[0])}}).catch(e=>setError(e instanceof Error?e.message:'Не удалось загрузить профиль'))},[accessToken]);
  useEffect(()=>{let active=true;setLoading(true);setError('');api.listExercises(accessToken,{muscle,environment}).then(out=>{if(active)setCatalog(out.items)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Не удалось загрузить упражнения')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[accessToken,muscle,environment]);
  useEffect(()=>setDrafts({}),[muscle,environment]);
  const visible=useMemo(()=>catalog.filter(item=>item.name.toLowerCase().includes(query.trim().toLowerCase())),[catalog,query]);
  const selected=catalog.filter(item=>drafts[item.id]);
  function toggle(exercise:Exercise){setDrafts(current=>{const next={...current};if(next[exercise.id])delete next[exercise.id];else next[exercise.id]={exercise_id:exercise.id,target_sets:exercise.default_sets,target_reps:exercise.rep_min,rest_seconds:exercise.rest_seconds};return next})}
  function update(id:string,key:'target_sets'|'target_reps'|'target_weight'|'rest_seconds',raw:string){setDrafts(current=>({...current,[id]:{...current[id],[key]:raw.trim()===''&&key==='target_weight'?undefined:Number(raw)}}))}
  async function create(){const minutes=Number(duration);const exercises=selected.map(item=>drafts[item.id]);if(!Number.isInteger(minutes)||minutes<10||minutes>180){setError('Длительность должна быть от 10 до 180 минут.');return}if(exercises.length===0){setError('Добавь хотя бы одно упражнение.');return}if(exercises.some(item=>!Number.isInteger(item.target_sets)||item.target_sets<1||item.target_sets>10||!Number.isInteger(item.target_reps)||item.target_reps<1||item.target_reps>200||!Number.isInteger(item.rest_seconds)||item.rest_seconds<0||item.rest_seconds>600||item.target_weight!==undefined&&(!Number.isFinite(item.target_weight)||item.target_weight<0||item.target_weight>1000))){setError('Проверь подходы, повторы, вес и отдых.');return}try{setSaving(true);setError('');onCreated(await api.createManualWorkout(accessToken,{muscle,environment,duration_minutes:minutes,exercises}))}catch(e){setError(e instanceof Error?e.message:'Не удалось создать тренировку')}finally{setSaving(false)}}
  return <ScrollView testID="manual-workout-screen" keyboardShouldPersistTaps="handled" contentContainerStyle={styles.container}>
    <Pressable accessibilityRole="button" onPress={onBack} style={styles.back}><Text style={styles.backText}>← Назад</Text></Pressable><Text accessibilityRole="header" style={styles.title}>Своя тренировка</Text><Text style={styles.muted}>Выбери упражнения и задай план каждого подхода.</Text>
    <Text style={styles.label}>Место</Text><View style={styles.wrap}>{environmentOptions.filter(([id])=>allowedEnvironments.includes(id)).map(([id,label])=><Choice key={id} label={label} active={environment===id} onPress={()=>setEnvironment(id)}/>)}</View>
    <Text style={styles.label}>Группа мышц</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.horizontal}>{muscleIds.map(id=><Choice key={id} label={muscleMeta[id].title} active={muscle===id} onPress={()=>setMuscle(id)}/>)}</ScrollView>
    <Text style={styles.label}>Длительность, минут</Text><TextInput accessibilityLabel="Длительность тренировки в минутах" value={duration} onChangeText={setDuration} keyboardType="number-pad" style={styles.input}/>
    <Text accessibilityRole="header" style={styles.section}>Упражнения · выбрано {selected.length}</Text><TextInput accessibilityLabel="Поиск упражнений" value={query} onChangeText={setQuery} placeholder="Поиск" placeholderTextColor={colors.textMuted} style={styles.input}/>
    {loading?<ActivityIndicator/>:visible.map(item=><View key={item.id} style={[styles.card,drafts[item.id]&&styles.selectedCard]}><Pressable accessibilityRole="checkbox" accessibilityState={{checked:Boolean(drafts[item.id])}} onPress={()=>toggle(item)} style={styles.exerciseHead}><Text style={styles.exerciseName}>{drafts[item.id]?'✓ ':''}{item.name}</Text><Text style={styles.muted}>{item.equipment.join(' · ')}</Text></Pressable>{drafts[item.id]?<View style={styles.fields}><Field label="Подходы" value={String(drafts[item.id].target_sets)} onChange={v=>update(item.id,'target_sets',v)}/><Field label="Повторы" value={String(drafts[item.id].target_reps)} onChange={v=>update(item.id,'target_reps',v)}/><Field label="Вес, кг" value={drafts[item.id].target_weight===undefined?'':String(drafts[item.id].target_weight)} onChange={v=>update(item.id,'target_weight',v)} decimal/><Field label="Отдых, сек" value={String(drafts[item.id].rest_seconds)} onChange={v=>update(item.id,'rest_seconds',v)}/></View>:null}</View>)}
    {!loading&&visible.length===0?<Text style={styles.muted}>Подходящих упражнений не найдено.</Text>:null}{error?<Text accessibilityRole="alert" style={styles.error}>{error}</Text>:null}<AppButton label="Создать план" loading={saving} disabled={selected.length===0} testID="manual-workout-create" onPress={()=>void create()}/>
  </ScrollView>
}
function Choice({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable accessibilityRole="radio" accessibilityState={{selected:active}} onPress={onPress} style={[styles.choice,active&&styles.choiceActive]}><Text style={[styles.choiceText,active&&styles.choiceTextActive]}>{label}</Text></Pressable>}
function Field({label,value,onChange,decimal=false}:{label:string;value:string;onChange:(value:string)=>void;decimal?:boolean}){return <View style={styles.field}><Text style={styles.smallLabel}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} keyboardType={decimal?'decimal-pad':'number-pad'} style={styles.smallInput}/></View>}
const styles=StyleSheet.create({container:{padding:spacing.lg,paddingBottom:spacing.xl,gap:spacing.md,backgroundColor:colors.background},back:{minHeight:control.minTouch,justifyContent:'center',alignSelf:'flex-start'},backText:{fontWeight:'800',color:colors.text},title:{fontSize:30,fontWeight:'900',color:colors.text},section:{fontSize:20,fontWeight:'900',color:colors.text},muted:{fontSize:13,lineHeight:19,color:colors.textMuted},label:{fontSize:13,fontWeight:'800',color:colors.text},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8},horizontal:{gap:8},choice:{minHeight:control.minTouch,paddingHorizontal:14,borderWidth:1,borderColor:colors.border,borderRadius:radius.pill,justifyContent:'center'},choiceActive:{backgroundColor:colors.primary,borderColor:colors.primary},choiceText:{fontWeight:'700',color:colors.text},choiceTextActive:{color:colors.inverse},input:{minHeight:control.minTouch,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:14,color:colors.text,fontSize:16},card:{borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,gap:spacing.sm},selectedCard:{borderColor:colors.primary},exerciseHead:{minHeight:control.minTouch,justifyContent:'center'},exerciseName:{fontSize:16,fontWeight:'900',color:colors.text},fields:{flexDirection:'row',flexWrap:'wrap',gap:8},field:{width:'48%',gap:4},smallLabel:{fontSize:11,fontWeight:'700',color:colors.textMuted},smallInput:{minHeight:control.minTouch,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:10,color:colors.text},error:{color:colors.danger,fontWeight:'700'}});
