import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {api,ProgramAnalytics,ProgramSession,TrainingProgram,WorkoutView} from '../api/client';
import {muscleMeta,MuscleId} from '../domain/muscles';
import {currentLocalDate} from '../domain/date';

const statusLabel:Record<string,string>={planned:'Запланировано',rescheduled:'Перенесено',missed:'Пропущено',completed:'Выполнено',skipped:'Пропущено'};
function muscleTitle(id:string){return (muscleMeta as Record<string,{title:string}>)[id]?.title ?? id}

export function ProgramDetailScreen({accessToken,programId,onBack,onWorkout,onArchived}:{accessToken:string;programId:string;onBack:()=>void;onWorkout:(workout:WorkoutView,muscle:MuscleId)=>void;onArchived:()=>void}){
 const [program,setProgram]=useState<TrainingProgram>();const [analytics,setAnalytics]=useState<ProgramAnalytics>();const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [message,setMessage]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const [p,a]=await Promise.all([api.getProgram(accessToken,programId),api.programAnalytics(accessToken,programId)]);setProgram(p);setAnalytics(a)}finally{setLoading(false)}},[accessToken,programId]);
 useEffect(()=>{void load()},[load]);
 const weeks=useMemo(()=>{const out=new Map<number,ProgramSession[]>();for(const s of program?.sessions??[]){out.set(s.week_number,[...(out.get(s.week_number)??[]),s])}return [...out.entries()]},[program]);
 async function start(s:ProgramSession){try{setBusy(s.id);const out=await api.createProgramWorkout(accessToken,s.id,currentLocalDate());onWorkout(out.workout,s.muscle as MuscleId)}finally{setBusy('')}}
 async function autoMove(s:ProgramSession){try{setBusy(s.id);const moved=await api.autoRescheduleProgramSession(accessToken,s.id);setMessage(`Перенесено на ${new Date(moved.planned_date).toLocaleDateString()}`);await load()}catch(e){setMessage(e instanceof Error?e.message:'Не удалось перенести')}finally{setBusy('')}}
 async function explain(s:ProgramSession){try{setBusy(s.id);const out=await api.explainProgramSession(accessToken,s.id);setMessage(out.explanation.message)}catch(e){setMessage(e instanceof Error?e.message:'Не удалось получить объяснение')}finally{setBusy('')}}
 async function archiveConfirmed(){try{setBusy('archive');await api.archiveProgram(accessToken,programId);onArchived()}catch(e){setMessage(e instanceof Error?e.message:'Не удалось архивировать программу')}finally{setBusy('')}}
 function archive(){Alert.alert('Архивировать программу?','Она исчезнет из активных программ, но история и выполненные тренировки сохранятся.',[{text:'Отмена',style:'cancel'},{text:'Архивировать',style:'destructive',onPress:()=>{void archiveConfirmed()}}])}
 if(loading&&!program)return <View style={styles.center}><ActivityIndicator/></View>;
 if(!program)return <View style={styles.center}><Text>Программа не найдена.</Text></View>;
 return <ScrollView contentContainerStyle={styles.container}><View style={styles.top}><Pressable onPress={onBack}><Text style={styles.back}>← Программы</Text></Pressable>{program.program.status==='active'?<Pressable accessibilityRole="button" accessibilityLabel="Архивировать программу" accessibilityState={{disabled:busy==='archive'}} testID="program-archive" disabled={busy==='archive'} onPress={archive} style={styles.touchAction}><Text style={styles.archive}>{busy==='archive'?'…':'Архивировать'}</Text></Pressable>:null}</View>
 <Text style={styles.eyebrow}>PROGRAM ENGINE</Text><Text style={styles.title}>{program.program.title}</Text><Text style={styles.sub}>{program.program.environment} · цель {program.program.goal_type}</Text>
 <View style={styles.analytics}><Metric title={`${analytics?.adherence_percent??0}%`} text="adherence"/><Metric title={`${analytics?.completed_sessions??0}/${analytics?.planned_sessions??program.sessions.length}`} text="сессий"/><Metric title={`${analytics?.current_week??1}/${program.program.weeks}`} text="неделя"/></View>
 {message?<View style={styles.aiBox}><Text style={styles.aiLabel}>AI / SYSTEM</Text><Text style={styles.aiText}>{message}</Text><Pressable onPress={()=>setMessage('')}><Text style={styles.close}>Закрыть</Text></Pressable></View>:null}
 {weeks.map(([week,sessions])=><View key={week} style={styles.week}><View style={styles.weekHead}><Text style={styles.weekTitle}>Неделя {week}</Text>{sessions.some(x=>x.is_deload)?<Text style={styles.deload}>DELOAD</Text>:null}</View>{sessions.map(s=><View key={s.id} style={[styles.session,s.status==='completed'&&styles.done,s.status==='missed'&&styles.missed]}><View style={{flex:1,gap:3}}><Text style={styles.date}>{new Date(s.planned_date).toLocaleDateString()} · {statusLabel[s.status]??s.status}</Text><Text style={styles.muscle}>{muscleTitle(s.muscle)}{s.secondary_muscle?` + ${muscleTitle(s.secondary_muscle)}`:''}</Text><Text style={styles.meta}>{s.planned_sets} плановых подходов · объём ×{s.volume_multiplier.toFixed(2)} · интенсивность ×{s.intensity_multiplier.toFixed(2)}</Text>{s.adaptation_reason?<Text style={styles.reason}>{s.adaptation_reason}</Text>:null}</View><View style={styles.actions}>{s.status!=='completed'&&!s.workout_id?<Pressable accessibilityRole="button" accessibilityLabel={`Начать ${muscleTitle(s.muscle)}`} accessibilityState={{disabled:busy!==''}} testID={`program-start-${s.id}`} disabled={busy!==''} onPress={()=>start(s)} style={[styles.action,busy!==''&&styles.disabled]}><Text style={styles.actionText}>{busy===s.id?'…':'Старт'}</Text></Pressable>:null}{s.status==='missed'?<Pressable accessibilityRole="button" accessibilityLabel="Автоматически перенести тренировку" accessibilityState={{disabled:busy!==''}} testID={`program-auto-move-${s.id}`} disabled={busy!==''} onPress={()=>autoMove(s)} style={styles.touchAction}><Text style={styles.link}>{busy===s.id?'…':'Автоперенос'}</Text></Pressable>:null}{(s.is_deload||s.adaptation_reason)?<Pressable accessibilityRole="button" accessibilityLabel="Объяснить изменение программы" accessibilityState={{disabled:busy!==''}} testID={`program-explain-${s.id}`} disabled={busy!==''} onPress={()=>explain(s)} style={styles.touchAction}><Text style={styles.link}>{busy===s.id?'…':'Почему?'}</Text></Pressable>:null}</View></View>)}</View>)}
 </ScrollView>
}
function Metric({title,text}:{title:string;text:string}){return <View style={styles.metric}><Text style={styles.metricTitle}>{title}</Text><Text style={styles.metricText}>{text}</Text></View>}
const styles=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center'},container:{padding:20,gap:14},top:{flexDirection:'row',justifyContent:'space-between'},back:{fontWeight:'800'},archive:{fontWeight:'800',opacity:.5},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4,opacity:.45},title:{fontSize:28,fontWeight:'900'},sub:{fontSize:13,opacity:.58},analytics:{flexDirection:'row',gap:8},metric:{flex:1,borderWidth:1,borderRadius:14,padding:12},metricTitle:{fontSize:18,fontWeight:'900'},metricText:{fontSize:10,opacity:.55},aiBox:{backgroundColor:'#111',borderRadius:18,padding:16,gap:7},aiLabel:{color:'#fff',fontSize:10,fontWeight:'900',letterSpacing:1.2,opacity:.5},aiText:{color:'#fff',fontSize:14,lineHeight:21},close:{color:'#fff',fontWeight:'800',opacity:.6},week:{gap:8,marginTop:4},weekHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},weekTitle:{fontSize:19,fontWeight:'900'},deload:{fontSize:10,fontWeight:'900',letterSpacing:1.1,borderWidth:1,borderRadius:10,paddingHorizontal:8,paddingVertical:4},session:{borderWidth:1,borderRadius:18,padding:14,flexDirection:'row',gap:10},done:{opacity:.55},missed:{borderStyle:'dashed'},date:{fontSize:11,fontWeight:'800',opacity:.52},muscle:{fontSize:17,fontWeight:'900'},meta:{fontSize:11,opacity:.58},reason:{fontSize:11,lineHeight:16,opacity:.55,marginTop:2},actions:{alignItems:'flex-end',gap:4},touchAction:{minHeight:44,justifyContent:'center',paddingHorizontal:4},disabled:{opacity:.45},action:{backgroundColor:'#111',paddingHorizontal:14,paddingVertical:9,borderRadius:12},actionText:{color:'#fff',fontWeight:'900'},link:{fontSize:11,fontWeight:'800'}})
