import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {api,ProgramAnalytics,ProgramSession,TrainingProgram,WorkoutView} from '../api/client';
import {muscleMeta,MuscleId} from '../domain/muscles';
import {currentLocalDate} from '../domain/date';
import {AppButton} from '../components/AppButton';
import {colors,control,radius,spacing} from '../theme/tokens';

const statusLabel:Record<string,string>={planned:'Запланировано',rescheduled:'Перенесено',missed:'Пропущено',completed:'Выполнено',skipped:'Пропущено'};
function muscleTitle(id:string){return (muscleMeta as Record<string,{title:string}>)[id]?.title ?? id}

export function ProgramDetailScreen({accessToken,programId,onBack,onWorkout,onArchived}:{accessToken:string;programId:string;onBack:()=>void;onWorkout:(workout:WorkoutView,muscle:MuscleId)=>void;onArchived:()=>void}){
 const [program,setProgram]=useState<TrainingProgram>();const [analytics,setAnalytics]=useState<ProgramAnalytics>();const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [message,setMessage]=useState('');const [loadError,setLoadError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setLoadError('');try{const [p,a]=await Promise.all([api.getProgram(accessToken,programId),api.programAnalytics(accessToken,programId)]);setProgram(p);setAnalytics(a)}catch(e){setLoadError(e instanceof Error?e.message:'Не удалось загрузить программу.')}finally{setLoading(false)}},[accessToken,programId]);
 useEffect(()=>{void load()},[load]);
 const weeks=useMemo(()=>{const out=new Map<number,ProgramSession[]>();for(const s of program?.sessions??[]){out.set(s.week_number,[...(out.get(s.week_number)??[]),s])}return [...out.entries()]},[program]);
 async function start(s:ProgramSession){try{setBusy(s.id);const out=await api.createProgramWorkout(accessToken,s.id,currentLocalDate());onWorkout(out.workout,s.muscle as MuscleId)}finally{setBusy('')}}
 async function autoMove(s:ProgramSession){try{setBusy(s.id);const moved=await api.autoRescheduleProgramSession(accessToken,s.id);setMessage(`Перенесено на ${new Date(moved.planned_date).toLocaleDateString()}`);await load()}catch(e){setMessage(e instanceof Error?e.message:'Не удалось перенести')}finally{setBusy('')}}
 async function explain(s:ProgramSession){try{setBusy(s.id);const out=await api.explainProgramSession(accessToken,s.id);setMessage(out.explanation.message)}catch(e){setMessage(e instanceof Error?e.message:'Не удалось получить объяснение')}finally{setBusy('')}}
 async function archiveConfirmed(){try{setBusy('archive');await api.archiveProgram(accessToken,programId);onArchived()}catch(e){setMessage(e instanceof Error?e.message:'Не удалось архивировать программу')}finally{setBusy('')}}
 function archive(){Alert.alert('Архивировать программу?','Она исчезнет из активных программ, но история и выполненные тренировки сохранятся.',[{text:'Отмена',style:'cancel'},{text:'Архивировать',style:'destructive',onPress:()=>{void archiveConfirmed()}}])}
 if(loading&&!program)return <View accessibilityRole="progressbar" accessibilityLabel="Загрузка программы" style={styles.center}><ActivityIndicator color={colors.primary}/><Text style={styles.muted}>Загружаем программу…</Text></View>;
 if(!program)return <View style={styles.center}><Text accessibilityRole="header" style={styles.errorTitle}>Программа недоступна</Text><Text accessibilityRole="alert" style={styles.muted}>{loadError||'Возможно, она была удалена или перемещена в архив.'}</Text><AppButton label="Повторить" variant="secondary" testID="program-detail-retry" onPress={()=>void load()}/><AppButton label="К программам" variant="text" onPress={onBack}/></View>;
 return <ScrollView testID="program-detail-screen" contentContainerStyle={styles.container}><View style={styles.top}><Pressable accessibilityRole="button" accessibilityLabel="Вернуться к программам" hitSlop={8} onPress={onBack} style={styles.touchAction}><Text style={styles.back}>← Программы</Text></Pressable>{program.program.status==='active'?<Pressable accessibilityRole="button" accessibilityLabel="Архивировать программу" accessibilityState={{disabled:busy==='archive',busy:busy==='archive'}} testID="program-archive" disabled={busy==='archive'} onPress={archive} style={[styles.touchAction,busy==='archive'&&styles.disabled]}><Text style={styles.archive}>{busy==='archive'?'Архивирую…':'Архивировать'}</Text></Pressable>:null}</View>
 <Text style={styles.eyebrow}>ПЛАН ТРЕНИРОВОК</Text><Text accessibilityRole="header" style={styles.title}>{program.program.title}</Text><Text style={styles.sub}>{environmentLabel(program.program.environment)} · цель: {goalLabel(program.program.goal_type)}</Text>
 <View style={styles.analytics}><Metric title={`${analytics?.adherence_percent??0}%`} text="выполнение"/><Metric title={`${analytics?.completed_sessions??0}/${analytics?.planned_sessions??program.sessions.length}`} text="тренировок"/><Metric title={`${analytics?.current_week??1}/${program.program.weeks}`} text="неделя"/></View>
 {message?<View accessibilityRole="alert" style={styles.aiBox}><Text style={styles.aiLabel}>ОБНОВЛЕНИЕ ПРОГРАММЫ</Text><Text style={styles.aiText}>{message}</Text><Pressable accessibilityRole="button" accessibilityLabel="Закрыть сообщение" onPress={()=>setMessage('')} style={styles.touchAction}><Text style={styles.close}>Закрыть</Text></Pressable></View>:null}
 {loadError?<View accessibilityRole="alert" style={styles.inlineError}><Text style={styles.errorText}>{loadError}</Text><Pressable accessibilityRole="button" onPress={()=>void load()} style={styles.touchAction}><Text style={styles.link}>Повторить</Text></Pressable></View>:null}
 {weeks.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>В программе пока нет тренировок</Text><Text style={styles.muted}>Обнови экран чуть позже или создай новую программу.</Text></View>:null}
 {weeks.map(([week,sessions])=><View key={week} style={styles.week}><View style={styles.weekHead}><Text style={styles.weekTitle}>Неделя {week}</Text>{sessions.some(x=>x.is_deload)?<Text style={styles.deload}>DELOAD</Text>:null}</View>{sessions.map(s=><View key={s.id} style={[styles.session,s.status==='completed'&&styles.done,s.status==='missed'&&styles.missed]}><View style={{flex:1,gap:3}}><Text style={styles.date}>{new Date(s.planned_date).toLocaleDateString()} · {statusLabel[s.status]??s.status}</Text><Text style={styles.muscle}>{muscleTitle(s.muscle)}{s.secondary_muscle?` + ${muscleTitle(s.secondary_muscle)}`:''}</Text><Text style={styles.meta}>{s.planned_sets} плановых подходов · объём ×{s.volume_multiplier.toFixed(2)} · интенсивность ×{s.intensity_multiplier.toFixed(2)}</Text>{s.adaptation_reason?<Text style={styles.reason}>{s.adaptation_reason}</Text>:null}</View><View style={styles.actions}>{s.status!=='completed'&&!s.workout_id?<Pressable accessibilityRole="button" accessibilityLabel={`Начать ${muscleTitle(s.muscle)}`} accessibilityState={{disabled:busy!==''}} testID={`program-start-${s.id}`} disabled={busy!==''} onPress={()=>start(s)} style={[styles.action,busy!==''&&styles.disabled]}><Text style={styles.actionText}>{busy===s.id?'…':'Старт'}</Text></Pressable>:null}{s.status==='missed'?<Pressable accessibilityRole="button" accessibilityLabel="Автоматически перенести тренировку" accessibilityState={{disabled:busy!==''}} testID={`program-auto-move-${s.id}`} disabled={busy!==''} onPress={()=>autoMove(s)} style={styles.touchAction}><Text style={styles.link}>{busy===s.id?'…':'Автоперенос'}</Text></Pressable>:null}{(s.is_deload||s.adaptation_reason)?<Pressable accessibilityRole="button" accessibilityLabel="Объяснить изменение программы" accessibilityState={{disabled:busy!==''}} testID={`program-explain-${s.id}`} disabled={busy!==''} onPress={()=>explain(s)} style={styles.touchAction}><Text style={styles.link}>{busy===s.id?'…':'Почему?'}</Text></Pressable>:null}</View></View>)}</View>)}
 </ScrollView>
}
function Metric({title,text}:{title:string;text:string}){return <View style={styles.metric}><Text style={styles.metricTitle}>{title}</Text><Text style={styles.metricText}>{text}</Text></View>}
function environmentLabel(value:string){return value==='gym'?'Зал':value==='home'?'Дома':value==='band'?'Резинки':value}
function goalLabel(value:string){return value==='hypertrophy'?'рост мышц':value==='strength'?'сила':value==='fat_loss'?'снижение веса':value}
const styles=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center',padding:spacing.lg,gap:spacing.md,backgroundColor:colors.background},container:{padding:spacing.lg,paddingBottom:spacing.xl,gap:spacing.md,backgroundColor:colors.background},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},back:{fontWeight:'800',color:colors.text},archive:{fontWeight:'800',color:colors.danger},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:colors.textMuted},title:{fontSize:28,lineHeight:34,fontWeight:'900',color:colors.text},sub:{fontSize:13,lineHeight:18,color:colors.textMuted},analytics:{flexDirection:'row',gap:spacing.sm},metric:{flex:1,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:12},metricTitle:{fontSize:18,fontWeight:'900',color:colors.text},metricText:{fontSize:10,color:colors.textMuted,marginTop:2},aiBox:{backgroundColor:colors.primary,borderRadius:radius.lg,padding:spacing.md,gap:spacing.sm},aiLabel:{color:colors.inverse,fontSize:10,fontWeight:'900',letterSpacing:1.2,opacity:.65},aiText:{color:colors.inverse,fontSize:14,lineHeight:21},close:{color:colors.inverse,fontWeight:'800',opacity:.8},week:{gap:spacing.sm,marginTop:spacing.xs},weekHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},weekTitle:{fontSize:19,fontWeight:'900',color:colors.text},deload:{fontSize:10,fontWeight:'900',letterSpacing:1.1,borderWidth:1,borderColor:colors.border,borderRadius:radius.sm,paddingHorizontal:8,paddingVertical:4,color:colors.text},session:{borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:14,flexDirection:'row',flexWrap:'wrap',gap:10},done:{opacity:.55},missed:{borderStyle:'dashed',borderColor:colors.danger},date:{fontSize:11,fontWeight:'800',color:colors.textMuted},muscle:{fontSize:17,fontWeight:'900',color:colors.text},meta:{fontSize:11,lineHeight:16,color:colors.textMuted},reason:{fontSize:11,lineHeight:16,color:colors.textMuted,marginTop:2},actions:{alignItems:'flex-end',gap:4},touchAction:{minHeight:control.minTouch,justifyContent:'center',paddingHorizontal:4},disabled:{opacity:.45},action:{backgroundColor:colors.primary,minHeight:control.minTouch,paddingHorizontal:14,justifyContent:'center',borderRadius:radius.md},actionText:{color:colors.inverse,fontWeight:'900'},link:{fontSize:12,fontWeight:'800',color:colors.text},muted:{fontSize:13,lineHeight:19,color:colors.textMuted,textAlign:'center'},errorTitle:{fontSize:21,fontWeight:'900',color:colors.text},inlineError:{borderWidth:1,borderColor:colors.danger,borderRadius:radius.md,padding:spacing.md},errorText:{color:colors.danger,fontWeight:'700'},empty:{borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md,gap:spacing.xs},emptyTitle:{fontSize:17,fontWeight:'900',color:colors.text}})
