import React, {useCallback, useEffect, useMemo, useState} from 'react';
import {ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {api, BodyMeasurement, NutritionCorrelation, ProgressSummary} from '../api/client';
import {AppButton} from '../components/AppButton';
import {colors, control, radius, spacing} from '../theme/tokens';

function Delta({value,unit}:{value?:number;unit:string}){if(value===undefined)return <Text style={styles.small}>Недостаточно данных</Text>;return <Text accessibilityLabel={`Изменение ${value>0?'плюс ':''}${value.toFixed(1)} ${unit}`} style={styles.delta}>{value>0?'+':''}{value.toFixed(1)} {unit}</Text>}
const parseOptional=(value:string)=>value.trim()?Number(value.replace(',','.')):undefined;

export function ProgressScreen({accessToken,onBack,onBodyScan,onTechnique}:{accessToken:string;onBack:()=>void;onBodyScan:()=>void;onTechnique:()=>void}){
  const [summary,setSummary]=useState<ProgressSummary|null>(null);const [history,setHistory]=useState<BodyMeasurement[]>([]);const [correlation,setCorrelation]=useState<NutritionCorrelation|null>(null);const [weight,setWeight]=useState('');const [waist,setWaist]=useState('');const [arm,setArm]=useState('');const [refreshing,setRefreshing]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [formError,setFormError]=useState('');
  const load=useCallback(async()=>{try{setError('');const [s,h,c]=await Promise.all([api.progressSummary(accessToken,30),api.measurementHistory(accessToken,30),api.nutritionCorrelation(accessToken,30).catch(()=>null)]);setSummary(s);setHistory(h.items);setCorrelation(c);}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить прогресс')}finally{setLoading(false)}},[accessToken]);useEffect(()=>{void load()},[load]);
  async function refresh(){setRefreshing(true);await load();setRefreshing(false)}
  const values={weight:parseOptional(weight),waist:parseOptional(waist),arm:parseOptional(arm)};
  const hasValue=Object.values(values).some(v=>v!==undefined);
  function validate(){if(!hasValue)return 'Введите хотя бы один замер.';if(values.weight!==undefined&&(values.weight<20||values.weight>400))return 'Вес должен быть от 20 до 400 кг.';if(values.waist!==undefined&&(values.waist<30||values.waist>300))return 'Талия должна быть от 30 до 300 см.';if(values.arm!==undefined&&(values.arm<10||values.arm>100))return 'Обхват руки должен быть от 10 до 100 см.';if(Object.values(values).some(v=>v!==undefined&&!Number.isFinite(v)))return 'Используйте только числа.';return ''}
  async function save(){const invalid=validate();setFormError(invalid);if(invalid)return;try{setSaving(true);setError('');await api.logMeasurement(accessToken,{weight_kg:values.weight,waist_cm:values.waist,arm_cm:values.arm});setWeight('');setWaist('');setArm('');await load();}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить замер')}finally{setSaving(false)}}
  const weights=useMemo(()=>history.filter(x=>x.weight_kg!==undefined),[history]);const min=weights.length?Math.min(...weights.map(x=>x.weight_kg??0)):0;const max=weights.length?Math.max(...weights.map(x=>x.weight_kg??0)):1;const range=Math.max(1,max-min);const visibleWeights=weights.slice(-14);
  return <ScrollView contentContainerStyle={styles.container} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>} keyboardShouldPersistTaps="handled"><Pressable accessibilityRole="button" accessibilityLabel="Вернуться на главную" hitSlop={8} onPress={onBack} style={styles.navButton}><Text style={styles.back}>← Главная</Text></Pressable><Text style={styles.kicker}>BODY PROGRESS</Text><Text accessibilityRole="header" style={styles.title}>Прогресс</Text><Text style={styles.subtitle}>Смотрите тренд, а не отдельную цифру. Замеры зависят от времени суток, воды и условий измерения.</Text>
    {loading&&!summary?<View style={styles.loading} accessibilityLiveRegion="polite"><ActivityIndicator color={colors.text}/><Text style={styles.muted}>Загружаем замеры…</Text></View>:null}
    {!loading&&error&&!summary?<View style={styles.errorBox}><Text accessibilityRole="alert" style={styles.error}>{error}</Text><AppButton label="Повторить" variant="secondary" onPress={()=>{setLoading(true);void load()}}/></View>:null}
    {!loading?<><View style={styles.hero}><View><Text style={styles.label}>Текущий вес</Text><Text style={styles.heroValue}>{summary?.weight_current_kg?.toFixed(1)??'—'} <Text style={styles.unit}>кг</Text></Text></View><Delta value={summary?.weight_delta_kg} unit="кг за 30 дней"/></View>
    <View style={styles.cards}><View style={styles.stat}><Text style={styles.label}>Талия</Text><Text style={styles.statValue}>{summary?.waist_current_cm?.toFixed(1)??'—'} см</Text><Delta value={summary?.waist_delta_cm} unit="см"/></View><View style={styles.stat}><Text style={styles.label}>Замеров</Text><Text style={styles.statValue}>{summary?.points??0}</Text><Text style={styles.small}>за 30 дней</Text></View></View>
    <Text style={styles.section}>Вес · 30 дней</Text>{visibleWeights.length>1?<View style={styles.chart} accessibilityLabel={`График веса: от ${visibleWeights[0].weight_kg?.toFixed(1)} до ${visibleWeights[visibleWeights.length-1].weight_kg?.toFixed(1)} килограмма`}>{visibleWeights.map((x,i)=>{const h=18+(((x.weight_kg??min)-min)/range)*70;return <View key={x.id} style={styles.barWrap}><View style={[styles.bar,{height:h}]}/><Text style={styles.barLabel}>{i===0||i===visibleWeights.length-1?(x.weight_kg??0).toFixed(1):''}</Text></View>})}</View>:<View style={styles.empty}><Text style={styles.emptyTitle}>Нужны два замера</Text><Text style={styles.muted}>Добавьте ещё один замер веса, чтобы увидеть тренд.</Text></View>}
    <Text style={styles.section}>Инструменты</Text><View style={styles.toolCard}><Text style={styles.corrTitle}>Фото-прогресс формы</Text><Text style={styles.muted}>Три приватных ракурса в одинаковых условиях. Фото помогают сравнивать контрольные точки, но не ставят диагноз.</Text><AppButton label="Открыть Body Scan" testID="progress-body-scan" onPress={onBodyScan}/></View><View style={styles.toolCard}><Text style={styles.corrTitle}>Pose-анализ подхода</Text><Text style={styles.muted}>Короткое видео даст ориентировочную оценку повторений, амплитуды, темпа и симметрии. При боли остановитесь и обратитесь к специалисту.</Text><AppButton label="Анализировать технику" testID="progress-technique" onPress={onTechnique}/></View>
    <Text style={styles.section}>Новый замер</Text><View style={styles.form}><TextInput accessibilityLabel="Вес в килограммах" value={weight} onChangeText={value=>{setWeight(value);setFormError('')}} keyboardType="decimal-pad" maxLength={7} placeholder="Вес, кг" placeholderTextColor={colors.textMuted} style={styles.input}/><TextInput accessibilityLabel="Обхват талии в сантиметрах" value={waist} onChangeText={value=>{setWaist(value);setFormError('')}} keyboardType="decimal-pad" maxLength={7} placeholder="Талия, см" placeholderTextColor={colors.textMuted} style={styles.input}/><TextInput accessibilityLabel="Обхват руки в сантиметрах" value={arm} onChangeText={value=>{setArm(value);setFormError('')}} keyboardType="decimal-pad" maxLength={7} placeholder="Бицепс, см" placeholderTextColor={colors.textMuted} style={styles.input}/>{formError?<Text accessibilityRole="alert" style={styles.error}>{formError}</Text>:null}<AppButton label="Сохранить замер" loading={saving} disabled={!hasValue} onPress={()=>void save()}/></View>
    {correlation?<><Text style={styles.section}>Питание × тренировки</Text><View style={styles.corr}><Text style={styles.disclaimer}>Наблюдаемая связь по записям за 30 дней — не доказательство причины.</Text><Text style={styles.corrTitle}>Тренировочные дни</Text><Text style={styles.corrValue}>{Math.round(correlation.avg_training_calories)} kcal · Б {Math.round(correlation.avg_training_protein_g)} г</Text><Text style={styles.small}>{correlation.logged_training_days} дней с записями</Text><View style={styles.divider}/><Text style={styles.corrTitle}>Дни отдыха</Text><Text style={styles.corrValue}>{Math.round(correlation.avg_rest_calories)} kcal · Б {Math.round(correlation.avg_rest_protein_g)} г</Text><Text style={styles.small}>{correlation.logged_rest_days} дней с записями</Text></View></>:null}{error&&summary?<Text accessibilityRole="alert" style={styles.error}>{error}</Text>:null}</>:null}
  </ScrollView>;
}
const styles=StyleSheet.create({container:{padding:spacing.lg,gap:spacing.md,backgroundColor:colors.background},navButton:{minHeight:control.minTouch,justifyContent:'center',alignSelf:'flex-start'},back:{fontWeight:'800',color:colors.text},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.3,color:colors.textMuted},title:{fontSize:32,fontWeight:'900',color:colors.text},subtitle:{fontSize:13,lineHeight:19,color:colors.textMuted},loading:{minHeight:120,alignItems:'center',justifyContent:'center',gap:spacing.sm},muted:{fontSize:12,lineHeight:18,color:colors.textMuted},hero:{borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end',gap:spacing.sm},label:{fontSize:11,fontWeight:'800',color:colors.textMuted},heroValue:{fontSize:38,fontWeight:'900',marginTop:4,color:colors.text},unit:{fontSize:15,fontWeight:'800'},delta:{fontSize:12,fontWeight:'800',color:colors.text},cards:{flexDirection:'row',gap:spacing.sm},stat:{flex:1,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md,gap:4},statValue:{fontSize:20,fontWeight:'900',color:colors.text},small:{fontSize:10,lineHeight:15,color:colors.textMuted},section:{fontSize:19,fontWeight:'900',color:colors.text,marginTop:3},chart:{height:120,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:12,flexDirection:'row',alignItems:'flex-end',gap:5},barWrap:{flex:1,alignItems:'center',justifyContent:'flex-end'},bar:{width:'100%',minWidth:5,backgroundColor:colors.primary,borderRadius:5},barLabel:{fontSize:8,fontWeight:'700',height:12,marginTop:3,color:colors.text},empty:{backgroundColor:colors.surfaceMuted,borderRadius:radius.md,padding:spacing.md,gap:spacing.xs},emptyTitle:{fontWeight:'900',color:colors.text},toolCard:{borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,gap:spacing.sm},form:{gap:spacing.sm},input:{minHeight:control.minTouch,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:12,fontWeight:'700',color:colors.text},corr:{borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,gap:4},corrTitle:{fontSize:14,fontWeight:'800',color:colors.text},corrValue:{fontSize:17,fontWeight:'900',color:colors.text},disclaimer:{fontSize:11,lineHeight:16,color:colors.textMuted,marginBottom:spacing.sm},divider:{height:1,backgroundColor:colors.border,marginVertical:spacing.sm},errorBox:{borderWidth:1,borderColor:colors.danger,borderRadius:radius.md,padding:spacing.md,gap:spacing.sm},error:{fontSize:12,lineHeight:18,fontWeight:'700',color:colors.danger}});
