import React, {useCallback, useEffect, useMemo, useState} from 'react';
import {Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {api, BodyMeasurement, NutritionCorrelation, ProgressSummary} from '../api/client';

function Delta({value,unit}:{value?:number;unit:string}){if(value===undefined)return null;return <Text style={styles.delta}>{value>0?'+':''}{value.toFixed(1)} {unit}</Text>}
export function ProgressScreen({accessToken,onBack,onBodyScan,onTechnique}:{accessToken:string;onBack:()=>void;onBodyScan:()=>void;onTechnique:()=>void}){
  const [summary,setSummary]=useState<ProgressSummary|null>(null);const [history,setHistory]=useState<BodyMeasurement[]>([]);const [correlation,setCorrelation]=useState<NutritionCorrelation|null>(null);const [weight,setWeight]=useState('');const [waist,setWaist]=useState('');const [arm,setArm]=useState('');const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState('');
  const load=useCallback(async()=>{try{setError('');const [s,h,c]=await Promise.all([api.progressSummary(accessToken,30),api.measurementHistory(accessToken,30),api.nutritionCorrelation(accessToken,30).catch(()=>null)]);setSummary(s);setHistory(h.items);setCorrelation(c);}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить прогресс')}},[accessToken]);useEffect(()=>{void load()},[load]);
  async function refresh(){setRefreshing(true);await load();setRefreshing(false)}
  async function save(){const parse=(v:string)=>v.trim()?Number(v.replace(',','.')):undefined;try{await api.logMeasurement(accessToken,{weight_kg:parse(weight),waist_cm:parse(waist),arm_cm:parse(arm)});setWeight('');setWaist('');setArm('');await load();}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить замер')}}
  const weights=useMemo(()=>history.filter(x=>x.weight_kg!==undefined),[history]);const min=weights.length?Math.min(...weights.map(x=>x.weight_kg??0)):0;const max=weights.length?Math.max(...weights.map(x=>x.weight_kg??0)):1;const range=Math.max(1,max-min);
  return <ScrollView contentContainerStyle={styles.container} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>}><Pressable onPress={onBack}><Text style={styles.back}>← Главная</Text></Pressable><Text style={styles.kicker}>BODY PROGRESS</Text><Text style={styles.title}>Прогресс</Text>
    <View style={styles.hero}><View><Text style={styles.label}>Текущий вес</Text><Text style={styles.heroValue}>{summary?.weight_current_kg?.toFixed(1)??'—'} <Text style={styles.unit}>кг</Text></Text></View><Delta value={summary?.weight_delta_kg} unit="кг / 30 дн."/></View>
    <View style={styles.cards}><View style={styles.stat}><Text style={styles.label}>Талия</Text><Text style={styles.statValue}>{summary?.waist_current_cm?.toFixed(1)??'—'} см</Text><Delta value={summary?.waist_delta_cm} unit="см"/></View><View style={styles.stat}><Text style={styles.label}>Замеров</Text><Text style={styles.statValue}>{summary?.points??0}</Text><Text style={styles.small}>за 30 дней</Text></View></View>
    {weights.length>1?<><Text style={styles.section}>Вес · 30 дней</Text><View style={styles.chart}>{weights.slice(-14).map((x,i)=>{const h=18+(((x.weight_kg??min)-min)/range)*70;return <View key={x.id} style={styles.barWrap}><View style={[styles.bar,{height:h}]}/><Text style={styles.barLabel}>{i===0||i===weights.slice(-14).length-1?(x.weight_kg??0).toFixed(1):''}</Text></View>})}</View></>:null}
    <Text style={styles.section}>Body Scan</Text><View style={styles.corr}><Text style={styles.corrTitle}>Фото-прогресс формы</Text><Text style={styles.small}>Три приватных ракурса: спереди, сбоку и сзади. Используем одинаковые условия съёмки для корректного сравнения.</Text><Pressable testID="progress-body-scan" accessibilityRole="button" onPress={onBodyScan} style={styles.primary}><Text style={styles.primaryText}>Открыть Body Scan</Text></Pressable></View><Text style={styles.section}>Техника упражнений</Text><View style={styles.corr}><Text style={styles.corrTitle}>Pose-анализ подхода</Text><Text style={styles.small}>Запишите короткое видео: приложение посчитает повторения, амплитуду, темп, симметрию и стабильность.</Text><Pressable testID="progress-technique" accessibilityRole="button" onPress={onTechnique} style={styles.primary}><Text style={styles.primaryText}>Анализировать технику</Text></Pressable></View><Text style={styles.section}>Новый замер</Text><View style={styles.form}><TextInput value={weight} onChangeText={setWeight} keyboardType="decimal-pad" placeholder="Вес, кг" style={styles.input}/><TextInput value={waist} onChangeText={setWaist} keyboardType="decimal-pad" placeholder="Талия, см" style={styles.input}/><TextInput value={arm} onChangeText={setArm} keyboardType="decimal-pad" placeholder="Бицепс, см" style={styles.input}/><Pressable onPress={()=>void save()} style={styles.primary}><Text style={styles.primaryText}>Сохранить замер</Text></Pressable></View>
    {correlation?<><Text style={styles.section}>Питание × тренировки</Text><View style={styles.corr}><Text style={styles.corrTitle}>Тренировочные дни</Text><Text style={styles.corrValue}>{Math.round(correlation.avg_training_calories)} kcal · Б {Math.round(correlation.avg_training_protein_g)} г</Text><Text style={styles.small}>{correlation.logged_training_days} дней с записями</Text><View style={styles.divider}/><Text style={styles.corrTitle}>Дни отдыха</Text><Text style={styles.corrValue}>{Math.round(correlation.avg_rest_calories)} kcal · Б {Math.round(correlation.avg_rest_protein_g)} г</Text><Text style={styles.small}>{correlation.logged_rest_days} дней с записями</Text></View></>:null}{error?<Text style={styles.error}>{error}</Text>:null}
  </ScrollView>
}
const styles=StyleSheet.create({container:{padding:20,gap:14},back:{fontWeight:'800'},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.3,opacity:.5},title:{fontSize:32,fontWeight:'900'},hero:{borderWidth:1,borderRadius:22,padding:18,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},label:{fontSize:11,fontWeight:'850',opacity:.5},heroValue:{fontSize:38,fontWeight:'950',marginTop:4},unit:{fontSize:15,fontWeight:'800'},delta:{fontSize:12,fontWeight:'850'},cards:{flexDirection:'row',gap:10},stat:{flex:1,borderWidth:1,borderRadius:17,padding:14,gap:4},statValue:{fontSize:20,fontWeight:'900'},small:{fontSize:10,opacity:.5},section:{fontSize:19,fontWeight:'900',marginTop:3},chart:{height:120,borderWidth:1,borderRadius:18,padding:12,flexDirection:'row',alignItems:'flex-end',gap:5},barWrap:{flex:1,alignItems:'center',justifyContent:'flex-end'},bar:{width:'100%',minWidth:5,backgroundColor:'#111',borderRadius:5},barLabel:{fontSize:8,fontWeight:'700',height:12,marginTop:3},form:{gap:8},input:{borderWidth:1,borderRadius:13,paddingHorizontal:12,paddingVertical:10,fontWeight:'750'},primary:{backgroundColor:'#111',borderRadius:15,paddingVertical:14,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'900'},corr:{borderWidth:1,borderRadius:18,padding:14,gap:4},corrTitle:{fontSize:12,fontWeight:'850'},corrValue:{fontSize:17,fontWeight:'900'},divider:{height:1,backgroundColor:'#ddd',marginVertical:8},error:{fontSize:12,fontWeight:'700'}});
