import React, {useEffect, useMemo, useState} from 'react';
import {Pressable, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {api, FoodEntry, FoodItem, Recipe} from '../api/client';

type DraftItem={food:FoodItem;grams:string};
const meals:Array<{id:FoodEntry['meal_type'];title:string}>=[{id:'breakfast',title:'Завтрак'},{id:'lunch',title:'Обед'},{id:'dinner',title:'Ужин'},{id:'snack',title:'Перекус'}];
export function RecipesScreen({accessToken,onBack,onLogged}:{accessToken:string;onBack:()=>void;onLogged:()=>void}){
  const [recipes,setRecipes]=useState<Recipe[]>([]);const [name,setName]=useState('');const [query,setQuery]=useState('');const [foods,setFoods]=useState<FoodItem[]>([]);const [draft,setDraft]=useState<DraftItem[]>([]);const [meal,setMeal]=useState<FoodEntry['meal_type']>('breakfast');const [error,setError]=useState('');
  async function load(){try{setRecipes((await api.recipes(accessToken)).items);}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить рецепты')}}
  useEffect(()=>{void load();},[accessToken]);
  async function search(){try{setFoods((await api.searchFoods(accessToken,query,12)).items);}catch(e){setError(e instanceof Error?e.message:'Ошибка поиска')}}
  function add(food:FoodItem){if(draft.some(x=>x.food.id===food.id))return;setDraft(x=>[...x,{food,grams:String(Math.round(food.serving_g||100))}]);}
  const total=useMemo(()=>draft.reduce((acc,x)=>{const g=Number(x.grams.replace(',','.'))||0;const f=g/100;return {kcal:acc.kcal+x.food.kcal_per_100g*f,p:acc.p+x.food.protein_per_100g*f,f:acc.f+x.food.fat_per_100g*f,c:acc.c+x.food.carbs_per_100g*f};},{kcal:0,p:0,f:0,c:0}),[draft]);
  async function save(){try{setError('');await api.createRecipe(accessToken,{name,items:draft.map(x=>({food_id:x.food.id,quantity_g:Number(x.grams.replace(',','.'))}))});setName('');setDraft([]);await load();}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить рецепт')}}
  async function log(recipe:Recipe){try{await api.logRecipe(accessToken,recipe.id,{meal_type:meal,scale:1});onLogged();}catch(e){setError(e instanceof Error?e.message:'Не удалось добавить рецепт')}}
  return <ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled"><Pressable onPress={onBack}><Text style={styles.back}>← Питание</Text></Pressable><Text style={styles.kicker}>БЫСТРАЯ ЕДА</Text><Text style={styles.title}>Рецепты</Text>
    <View style={styles.meals}>{meals.map(x=><Pressable key={x.id} onPress={()=>setMeal(x.id)} style={[styles.pill,meal===x.id&&styles.active]}><Text style={[styles.pillText,meal===x.id&&styles.white]}>{x.title}</Text></Pressable>)}</View>
    {recipes.length>0?<View style={styles.list}>{recipes.map(r=><View key={r.id} style={styles.card}><View style={{flex:1}}><Text style={styles.cardTitle}>{r.name}</Text><Text style={styles.meta}>{r.items.length} продуктов · {Math.round(r.items.reduce((a,x)=>a+x.calories,0))} kcal</Text></View><Pressable onPress={()=>void log(r)} style={styles.addBtn}><Text style={styles.addText}>+ дневник</Text></Pressable></View>)}</View>:<Text style={styles.muted}>Сохранённых рецептов пока нет.</Text>}
    <Text style={styles.section}>Создать рецепт</Text><TextInput value={name} onChangeText={setName} placeholder="Название блюда" style={styles.input}/><View style={styles.search}><TextInput value={query} onChangeText={setQuery} onSubmitEditing={()=>void search()} placeholder="Найти ингредиент" style={[styles.input,{flex:1}]}/><Pressable onPress={()=>void search()} style={styles.dark}><Text style={styles.whiteText}>Найти</Text></Pressable></View>
    {foods.map(food=><Pressable key={food.id} onPress={()=>add(food)} style={styles.food}><Text style={styles.foodTitle}>{food.name}</Text><Text style={styles.meta}>+ добавить</Text></Pressable>)}
    {draft.map((x,i)=><View key={x.food.id} style={styles.draft}><View style={{flex:1}}><Text style={styles.cardTitle}>{x.food.name}</Text><Text style={styles.meta}>{Math.round(x.food.kcal_per_100g*(Number(x.grams||0)/100))} kcal</Text></View><TextInput value={x.grams} onChangeText={v=>setDraft(d=>d.map((it,j)=>j===i?{...it,grams:v}:it))} keyboardType="decimal-pad" style={styles.grams}/><Text style={styles.unit}>г</Text></View>)}
    {draft.length>0?<><Text style={styles.total}>{Math.round(total.kcal)} kcal · Б {Math.round(total.p)} · Ж {Math.round(total.f)} · У {Math.round(total.c)}</Text><Pressable onPress={()=>void save()} style={styles.primary}><Text style={styles.primaryText}>Сохранить рецепт</Text></Pressable></>:null}{error?<Text style={styles.error}>{error}</Text>:null}
  </ScrollView>;
}
const styles=StyleSheet.create({container:{padding:20,gap:12},back:{fontWeight:'800'},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.3,opacity:.5},title:{fontSize:30,fontWeight:'900'},meals:{flexDirection:'row',flexWrap:'wrap',gap:6},pill:{borderWidth:1,borderRadius:99,paddingHorizontal:11,paddingVertical:7},active:{backgroundColor:'#111'},pillText:{fontWeight:'750',fontSize:12},white:{color:'#fff'},list:{gap:8},card:{borderWidth:1,borderRadius:16,padding:13,flexDirection:'row',alignItems:'center',gap:10},cardTitle:{fontWeight:'850'},meta:{fontSize:11,opacity:.5,marginTop:3},addBtn:{borderWidth:1,borderRadius:12,paddingHorizontal:10,paddingVertical:8},addText:{fontSize:11,fontWeight:'850'},muted:{opacity:.5},section:{fontSize:19,fontWeight:'900',marginTop:6},input:{borderWidth:1,borderRadius:13,paddingHorizontal:12,paddingVertical:10,fontWeight:'700'},search:{flexDirection:'row',gap:7},dark:{backgroundColor:'#111',borderRadius:13,paddingHorizontal:14,justifyContent:'center'},whiteText:{color:'#fff',fontWeight:'850'},food:{borderWidth:1,borderRadius:13,padding:11,flexDirection:'row',justifyContent:'space-between'},foodTitle:{fontWeight:'800'},draft:{borderWidth:1,borderRadius:14,padding:11,flexDirection:'row',alignItems:'center',gap:5},grams:{borderWidth:1,borderRadius:10,paddingHorizontal:8,paddingVertical:7,width:72,textAlign:'right',fontWeight:'800'},unit:{fontWeight:'700'},total:{fontWeight:'900',fontSize:16},primary:{backgroundColor:'#111',borderRadius:15,paddingVertical:14,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'900'},error:{fontWeight:'700',fontSize:12}});
