import React, {useEffect, useMemo, useState} from 'react';
import {ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {api, FoodEntry, FoodItem, Recipe} from '../api/client';
import {AppButton} from '../components/AppButton';
import {colors, control, radius, spacing} from '../theme/tokens';

type DraftItem={food:FoodItem;grams:string};
const meals:Array<{id:FoodEntry['meal_type'];title:string}>=[{id:'breakfast',title:'Завтрак'},{id:'lunch',title:'Обед'},{id:'dinner',title:'Ужин'},{id:'snack',title:'Перекус'}];
const numberValue=(value:string)=>Number(value.replace(',','.'));

export function RecipesScreen({accessToken,onBack,onLogged}:{accessToken:string;onBack:()=>void;onLogged:()=>void}){
  const [recipes,setRecipes]=useState<Recipe[]>([]);const [name,setName]=useState('');const [query,setQuery]=useState('');const [foods,setFoods]=useState<FoodItem[]>([]);const [draft,setDraft]=useState<DraftItem[]>([]);const [meal,setMeal]=useState<FoodEntry['meal_type']>('breakfast');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [searching,setSearching]=useState(false);const [saving,setSaving]=useState(false);const [loggingId,setLoggingId]=useState('');const [searched,setSearched]=useState(false);
  async function load(){try{setLoading(true);setError('');setRecipes((await api.recipes(accessToken)).items);}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить рецепты');}finally{setLoading(false)}}
  useEffect(()=>{void load();},[accessToken]);
  async function search(){try{setSearching(true);setSearched(true);setError('');setFoods((await api.searchFoods(accessToken,query.trim(),12)).items);}catch(e){setError(e instanceof Error?e.message:'Не удалось найти ингредиенты');}finally{setSearching(false)}}
  function add(food:FoodItem){if(draft.some(x=>x.food.id===food.id))return;setDraft(x=>[...x,{food,grams:String(Math.round(food.serving_g||100))}]);}
  const validDraft=draft.length>0&&draft.every(x=>{const n=numberValue(x.grams);return Number.isFinite(n)&&n>0&&n<=5000});
  const canSave=name.trim().length>=2&&validDraft&&!saving;
  const total=useMemo(()=>draft.reduce((acc,x)=>{const g=numberValue(x.grams)||0;const f=g/100;return {kcal:acc.kcal+x.food.kcal_per_100g*f,p:acc.p+x.food.protein_per_100g*f,f:acc.f+x.food.fat_per_100g*f,c:acc.c+x.food.carbs_per_100g*f};},{kcal:0,p:0,f:0,c:0}),[draft]);
  async function save(){if(!canSave)return;try{setSaving(true);setError('');await api.createRecipe(accessToken,{name:name.trim(),items:draft.map(x=>({food_id:x.food.id,quantity_g:numberValue(x.grams)}))});setName('');setDraft([]);setFoods([]);await load();}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить рецепт');}finally{setSaving(false)}}
  async function log(recipe:Recipe){try{setLoggingId(recipe.id);setError('');await api.logRecipe(accessToken,recipe.id,{meal_type:meal,scale:1});onLogged();}catch(e){setError(e instanceof Error?e.message:'Не удалось добавить рецепт');}finally{setLoggingId('')}}
  return <ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled"><Pressable accessibilityRole="button" accessibilityLabel="Вернуться к питанию" hitSlop={8} onPress={onBack} style={styles.navButton}><Text style={styles.back}>← Питание</Text></Pressable><Text style={styles.kicker}>БЫСТРАЯ ЕДА</Text><Text accessibilityRole="header" style={styles.title}>Рецепты</Text><Text style={styles.subtitle}>Сохраните часто повторяющийся набор продуктов и добавляйте его в дневник одним нажатием.</Text>
    <Text style={styles.label}>Добавить в</Text><View style={styles.meals} accessibilityRole="radiogroup">{meals.map(x=><Pressable key={x.id} accessibilityRole="radio" accessibilityState={{selected:meal===x.id}} onPress={()=>setMeal(x.id)} style={[styles.pill,meal===x.id&&styles.active]}><Text style={[styles.pillText,meal===x.id&&styles.white]}>{x.title}</Text></Pressable>)}</View>
    {loading?<View style={styles.state}><ActivityIndicator color={colors.text}/><Text style={styles.muted}>Загружаем рецепты…</Text></View>:null}
    {!loading&&recipes.length>0?<View style={styles.list}>{recipes.map(r=><View key={r.id} style={styles.card}><View style={styles.flex}><Text style={styles.cardTitle}>{r.name}</Text><Text style={styles.meta}>{r.items.length} продуктов · {Math.round(r.items.reduce((a,x)=>a+x.calories,0))} kcal</Text></View><AppButton label="В дневник" variant="secondary" loading={loggingId===r.id} disabled={Boolean(loggingId)&&loggingId!==r.id} onPress={()=>void log(r)}/></View>)}</View>:null}
    {!loading&&recipes.length===0&&!error?<View style={styles.empty}><Text style={styles.emptyTitle}>Рецептов пока нет</Text><Text style={styles.muted}>Создайте первый рецепт ниже — например, привычный завтрак.</Text></View>:null}
    <Text style={styles.section}>Создать рецепт</Text><TextInput accessibilityLabel="Название рецепта" value={name} onChangeText={setName} maxLength={100} placeholder="Название блюда" placeholderTextColor={colors.textMuted} style={styles.input}/><View style={styles.search}><TextInput accessibilityLabel="Поиск ингредиента" value={query} onChangeText={setQuery} onSubmitEditing={()=>void search()} returnKeyType="search" placeholder="Найти ингредиент" placeholderTextColor={colors.textMuted} style={[styles.input,styles.flex]}/><AppButton label="Найти" onPress={()=>void search()} disabled={searching}/></View>
    {searching?<View style={styles.state}><ActivityIndicator color={colors.text}/><Text style={styles.muted}>Ищем…</Text></View>:null}{!searching&&searched&&foods.length===0?<Text style={styles.muted}>Ингредиенты не найдены. Измените запрос.</Text>:null}
    {foods.map(food=>{const added=draft.some(x=>x.food.id===food.id);return <Pressable key={food.id} accessibilityRole="button" accessibilityLabel={`${added?'Уже добавлен':'Добавить'} ${food.name}`} accessibilityState={{disabled:added}} disabled={added} onPress={()=>add(food)} style={[styles.food,added&&styles.disabled]}><Text style={styles.foodTitle}>{food.name}</Text><Text style={styles.meta}>{added?'Добавлено':'+ Добавить'}</Text></Pressable>})}
    {draft.map((x,i)=>{const grams=numberValue(x.grams);const valid=Number.isFinite(grams)&&grams>0&&grams<=5000;return <View key={x.food.id} style={styles.draft}><View style={styles.flex}><Text style={styles.cardTitle}>{x.food.name}</Text><Text style={styles.meta}>{valid?`${Math.round(x.food.kcal_per_100g*(grams/100))} kcal`:'Введите 1–5000 г'}</Text></View><TextInput accessibilityLabel={`Количество ${x.food.name} в граммах`} value={x.grams} onChangeText={v=>setDraft(d=>d.map((it,j)=>j===i?{...it,grams:v}:it))} keyboardType="decimal-pad" maxLength={7} style={[styles.grams,!valid&&styles.invalid]}/><Text style={styles.unit}>г</Text><Pressable accessibilityRole="button" accessibilityLabel={`Удалить ${x.food.name}`} hitSlop={8} onPress={()=>setDraft(d=>d.filter((_,j)=>j!==i))} style={styles.remove}><Text style={styles.removeText}>×</Text></Pressable></View>})}
    {draft.length>0?<><Text accessibilityLiveRegion="polite" style={styles.total}>{Math.round(total.kcal)} kcal · Б {Math.round(total.p)} · Ж {Math.round(total.f)} · У {Math.round(total.c)}</Text>{name.trim().length<2?<Text style={styles.muted}>Введите название рецепта не короче 2 символов.</Text>:null}<AppButton label="Сохранить рецепт" loading={saving} disabled={!canSave} onPress={()=>void save()}/></>:null}{error?<View style={styles.errorBox}><Text accessibilityRole="alert" style={styles.error}>{error}</Text><AppButton label="Повторить загрузку" variant="text" onPress={()=>void load()}/></View>:null}
  </ScrollView>;
}
const styles=StyleSheet.create({container:{padding:spacing.lg,gap:spacing.sm,backgroundColor:colors.background},navButton:{minHeight:control.minTouch,justifyContent:'center',alignSelf:'flex-start'},back:{fontWeight:'800',color:colors.text},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.3,color:colors.textMuted},title:{fontSize:30,fontWeight:'900',color:colors.text},subtitle:{fontSize:14,lineHeight:20,color:colors.textMuted},label:{fontSize:12,fontWeight:'800',color:colors.textMuted},meals:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},pill:{minHeight:control.minTouch,borderWidth:1,borderColor:colors.border,borderRadius:radius.pill,paddingHorizontal:12,justifyContent:'center'},active:{backgroundColor:colors.primary,borderColor:colors.primary},pillText:{fontWeight:'800',fontSize:12,color:colors.text},white:{color:colors.inverse},state:{minHeight:control.minTouch,flexDirection:'row',alignItems:'center',gap:spacing.sm},list:{gap:spacing.sm},card:{borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md,flexDirection:'row',alignItems:'center',gap:spacing.sm},flex:{flex:1},cardTitle:{fontWeight:'800',color:colors.text},meta:{fontSize:11,color:colors.textMuted,marginTop:3},muted:{fontSize:13,lineHeight:19,color:colors.textMuted},empty:{backgroundColor:colors.surfaceMuted,borderRadius:radius.md,padding:spacing.md,gap:spacing.xs},emptyTitle:{fontWeight:'900',color:colors.text},section:{fontSize:19,fontWeight:'900',color:colors.text,marginTop:spacing.sm},input:{minHeight:control.minTouch,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:12,fontWeight:'700',color:colors.text},search:{flexDirection:'row',gap:spacing.sm},food:{minHeight:control.minTouch,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.sm,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.sm},foodTitle:{fontWeight:'800',color:colors.text,flex:1},disabled:{opacity:.45},draft:{minHeight:control.minTouch,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.sm,flexDirection:'row',alignItems:'center',gap:spacing.xs},grams:{minHeight:control.minTouch,borderWidth:1,borderColor:colors.border,borderRadius:radius.sm,paddingHorizontal:8,width:76,textAlign:'right',fontWeight:'800',color:colors.text},invalid:{borderColor:colors.danger},unit:{fontWeight:'700',color:colors.text},remove:{width:control.minTouch,height:control.minTouch,alignItems:'center',justifyContent:'center'},removeText:{fontSize:24,color:colors.danger},total:{fontWeight:'900',fontSize:16,color:colors.text},errorBox:{borderWidth:1,borderColor:colors.danger,borderRadius:radius.md,padding:spacing.sm,gap:spacing.xs},error:{fontWeight:'700',fontSize:12,color:colors.danger}});
