import React, {useMemo, useState} from 'react';
import {Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {AppButton} from '../components/AppButton';
import {colors,control,radius,spacing} from '../theme/tokens';

const environments = [['home', 'Дома'], ['gym', 'Зал'], ['band', 'Резина']] as const;
const equipment = [['bodyweight','Собственный вес'],['dumbbells','Гантели'],['barbell','Штанга'],['bench','Скамья'],['rack','Стойка'],['pullup_bar','Турник'],['cable_machine','Блоки'],['leg_machine','Тренажёры ног'],['kettlebell','Гиря'],['resistance_band','Резинки']] as const;

export function TrainingSetupScreen({onFinish}: {onFinish: (data: {environments: string[]; equipment: string[]; workouts: number; minutes: number}) => Promise<void>}) {
  const [places,setPlaces]=useState<string[]>(['gym']);const[gear,setGear]=useState<string[]>(['bodyweight','dumbbells','barbell','bench','rack','cable_machine','leg_machine']);const[workouts,setWorkouts]=useState(4);const[minutes,setMinutes]=useState(60);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
  const valid=useMemo(()=>places.length>0,[places]);const toggle=(value:string,current:string[],set:(v:string[])=>void)=>set(current.includes(value)?current.filter(x=>x!==value):[...current,value]);
  async function submit(){try{setLoading(true);setError('');await onFinish({environments:places,equipment:gear,workouts,minutes})}catch(e){setError(e instanceof Error?e.message:'Не удалось завершить настройку')}finally{setLoading(false)}}
  const chip=(id:string,label:string,selected:boolean,onPress:()=>void,testPrefix:string)=><Pressable key={id} testID={`${testPrefix}-${id}`} accessibilityRole="checkbox" accessibilityLabel={label} accessibilityState={{checked:selected}} hitSlop={3} onPress={onPress} style={({pressed})=>[styles.chip,selected&&styles.active,pressed&&styles.pressed]}><Text style={[styles.chipText,selected&&styles.activeText]}>{label}</Text></Pressable>;

  return <ScrollView testID="training-setup-screen" contentContainerStyle={styles.container}>
    <Text style={styles.step}>ШАГ 3 ИЗ 3</Text><Text accessibilityRole="header" style={styles.title}>Где ты тренируешься?</Text>
    <View style={styles.wrap}>{environments.map(([id,label])=>chip(id,label,places.includes(id),()=>toggle(id,places,setPlaces),'training-place'))}</View>
    <Text style={styles.section}>Оборудование</Text><View style={styles.wrap}>{equipment.map(([id,label])=>chip(id,label,gear.includes(id),()=>toggle(id,gear,setGear),'training-equipment'))}</View>
    <Text style={styles.section}>Тренировок в неделю</Text><View style={styles.wrap} accessibilityRole="radiogroup">{[2,3,4,5,6].map(v=><Pressable key={v} testID={`training-frequency-${v}`} accessibilityRole="radio" accessibilityLabel={`${v} тренировок в неделю`} accessibilityState={{selected:workouts===v}} onPress={()=>setWorkouts(v)} style={({pressed})=>[styles.number,workouts===v&&styles.active,pressed&&styles.pressed]}><Text style={[styles.chipText,workouts===v&&styles.activeText]}>{v}</Text></Pressable>)}</View>
    <Text style={styles.section}>Время на тренировку</Text><View style={styles.wrap} accessibilityRole="radiogroup">{[30,45,60,90].map(v=><Pressable key={v} testID={`training-duration-${v}`} accessibilityRole="radio" accessibilityLabel={`${v} минут на тренировку`} accessibilityState={{selected:minutes===v}} onPress={()=>setMinutes(v)} style={({pressed})=>[styles.chip,minutes===v&&styles.active,pressed&&styles.pressed]}><Text style={[styles.chipText,minutes===v&&styles.activeText]}>{v} мин</Text></Pressable>)}</View>
    {!!error&&<Text accessibilityRole="alert" style={styles.error}>{error}</Text>}<AppButton label="Начать тренироваться" testID="training-finish" loading={loading} disabled={!valid} onPress={()=>void submit()}/>
  </ScrollView>;
}
const styles=StyleSheet.create({container:{padding:spacing.xl,paddingTop:54,gap:spacing.md,flexGrow:1,backgroundColor:colors.background},step:{fontSize:12,fontWeight:'800',color:colors.textMuted,letterSpacing:1.4},title:{fontSize:32,fontWeight:'900',marginBottom:10,color:colors.text},section:{fontSize:17,fontWeight:'800',marginTop:12,color:colors.text},wrap:{flexDirection:'row',flexWrap:'wrap',gap:10},chip:{borderWidth:1,borderColor:colors.border,borderRadius:999,paddingHorizontal:16,minHeight:control.minTouch,justifyContent:'center',backgroundColor:colors.surface},number:{width:control.minTouch,height:control.minTouch,borderWidth:1,borderColor:colors.border,borderRadius:control.minTouch/2,alignItems:'center',justifyContent:'center',backgroundColor:colors.surface},active:{backgroundColor:colors.primary,borderColor:colors.primary},chipText:{fontWeight:'700',color:colors.text},activeText:{color:colors.inverse},pressed:{opacity:.72},error:{color:colors.danger,fontWeight:'700',marginTop:spacing.sm}});
