import React, {useCallback, useEffect, useState} from 'react';
import {ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View} from 'react-native';
import {api, WeeklyAIReport} from '../api/client';
import {AppButton} from '../components/AppButton';
import {colors, control, radius, spacing} from '../theme/tokens';

function List({title,items}:{title:string;items:string[]}){return <View style={styles.card}><Text style={styles.cardTitle}>{title}</Text>{items.length?items.map((x,i)=><View key={`${title}-${i}`} style={styles.itemRow}><Text style={styles.bullet}>•</Text><Text style={styles.item}>{x}</Text></View>):<Text style={styles.muted}>Пока недостаточно данных для этого раздела.</Text>}</View>}

export function WeeklyAIReportScreen({accessToken,onBack}:{accessToken:string;onBack:()=>void}){
  const[report,setReport]=useState<WeeklyAIReport|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);
  const load=useCallback(async()=>{try{setError('');setReport(await api.aiWeeklyReport(accessToken));}catch(e){setError(e instanceof Error?e.message:'Не удалось создать отчёт');}finally{setLoading(false);setRefreshing(false)}},[accessToken]);
  useEffect(()=>{void load()},[load]);
  return <ScrollView contentContainerStyle={styles.container} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load()}}/>}><Pressable accessibilityRole="button" accessibilityLabel="Вернуться к AI Coach" hitSlop={8} onPress={onBack} style={styles.navButton}><Text style={styles.back}>← AI Coach</Text></Pressable><Text style={styles.kicker}>WEEKLY INTELLIGENCE</Text><Text accessibilityRole="header" style={styles.title}>Отчёт недели</Text><Text style={styles.subtitle}>AI объясняет уже записанные данные. Отчёт не является медицинской рекомендацией и может быть неполным.</Text>
    {loading&&!report?<View style={styles.loading} accessibilityLiveRegion="polite"><ActivityIndicator color={colors.text}/><Text style={styles.muted}>Собираем тренировки, питание и прогресс…</Text></View>:null}
    {error&&!report?<View style={styles.errorBox}><Text accessibilityRole="alert" style={styles.error}>{error}</Text><AppButton label="Повторить" variant="secondary" onPress={()=>{setLoading(true);void load()}}/></View>:null}
    {report?<><View style={styles.period}><Text style={styles.periodLabel}>Период</Text><Text style={styles.periodValue}>{new Date(report.stats.from_date).toLocaleDateString('ru-RU')} — {new Date(report.stats.to_date).toLocaleDateString('ru-RU')}</Text></View><View style={styles.stats}><View style={styles.stat}><Text style={styles.num}>{report.stats.completed_workouts}</Text><Text style={styles.label}>тренировок</Text></View><View style={styles.stat}><Text style={styles.num}>{Math.round(report.stats.training_volume)}</Text><Text style={styles.label}>кг объёма</Text></View><View style={styles.stat}><Text style={styles.num}>{report.stats.new_prs}</Text><Text style={styles.label}>новых PR</Text></View></View><View style={styles.summary}><Text style={styles.summaryLabel}>AI-резюме</Text><Text style={styles.summaryText}>{report.summary}</Text>{report.stats.recovery_checkin_days ? <Text style={styles.recovery}>Recovery: {report.stats.recovery_checkin_days} дн. · средний readiness {Math.round(report.stats.avg_readiness ?? 0)}/100</Text> : <Text style={styles.recovery}>Недостаточно recovery-отметок для устойчивого вывода.</Text>}<Text style={styles.provider}>{report.provider} · {report.model}</Text></View><List title="Что получилось" items={report.wins}/><List title="Фокус" items={report.focus}/><List title="Следующие действия" items={report.next_actions}/>{error?<Text accessibilityRole="alert" style={styles.error}>{error}</Text>:null}</>:null}
  </ScrollView>;
}
const styles=StyleSheet.create({container:{padding:spacing.lg,gap:spacing.md,backgroundColor:colors.background},navButton:{minHeight:control.minTouch,justifyContent:'center',alignSelf:'flex-start'},back:{fontWeight:'800',color:colors.text},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.4,color:colors.textMuted},title:{fontSize:31,fontWeight:'900',color:colors.text},subtitle:{fontSize:13,lineHeight:19,color:colors.textMuted},loading:{minHeight:100,alignItems:'center',justifyContent:'center',gap:spacing.sm},period:{backgroundColor:colors.surfaceMuted,borderRadius:radius.md,padding:spacing.md,gap:spacing.xs},periodLabel:{fontSize:11,fontWeight:'800',color:colors.textMuted},periodValue:{fontWeight:'900',color:colors.text},stats:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md},stat:{flexGrow:1,minWidth:84},num:{fontSize:23,fontWeight:'900',color:colors.text},label:{fontSize:10,color:colors.textMuted},summary:{backgroundColor:colors.primary,borderRadius:radius.lg,padding:spacing.md,gap:spacing.sm},summaryLabel:{fontSize:11,fontWeight:'900',letterSpacing:1,color:colors.inverse,opacity:.7},summaryText:{color:colors.inverse,fontSize:15,lineHeight:21,fontWeight:'700'},recovery:{color:colors.inverse,fontSize:12,lineHeight:18,fontWeight:'700',opacity:.78},provider:{color:colors.inverse,fontSize:10,opacity:.55},card:{borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,gap:spacing.sm},cardTitle:{fontSize:16,fontWeight:'900',color:colors.text},itemRow:{flexDirection:'row',gap:spacing.sm,alignItems:'flex-start'},bullet:{color:colors.textMuted},item:{fontSize:13,lineHeight:19,color:colors.text,flex:1},muted:{fontSize:12,lineHeight:18,color:colors.textMuted},errorBox:{borderWidth:1,borderColor:colors.danger,borderRadius:radius.md,padding:spacing.md,gap:spacing.sm},error:{fontSize:12,lineHeight:18,fontWeight:'700',color:colors.danger}});
