import React, {useMemo, useState} from 'react';
import {Pressable, StyleSheet, Text, View} from 'react-native';
import {RecoveryMuscleStatus} from '../api/client';
import {MuscleId, muscleMeta} from '../domain/muscles';
import {colors, radius} from '../theme/tokens';

type Side='front'|'back';
type Point={muscle:MuscleId;top:number;left:number;width:number};
const points:Record<Side,Point[]>={front:[{muscle:'shoulders',top:58,left:18,width:104},{muscle:'chest',top:96,left:51,width:105},{muscle:'biceps',top:130,left:3,width:88},{muscle:'forearms',top:181,left:2,width:96},{muscle:'core',top:170,left:74,width:65},{muscle:'quads',top:264,left:50,width:111},{muscle:'calves',top:357,left:55,width:100}],back:[{muscle:'shoulders',top:58,left:18,width:104},{muscle:'back',top:103,left:56,width:96},{muscle:'triceps',top:137,left:3,width:88},{muscle:'forearms',top:181,left:2,width:96},{muscle:'glutes',top:228,left:64,width:88},{muscle:'hamstrings',top:285,left:35,width:143},{muscle:'calves',top:357,left:55,width:100}]};
function tone(status?:RecoveryMuscleStatus['status']){return status==='ready'?styles.ready:status==='moderate'?styles.moderate:styles.fatigued}
export function RecoveryBodyMap({items}:{items:RecoveryMuscleStatus[]}){
 const [side,setSide]=useState<Side>('front'); const byMuscle=useMemo(()=>Object.fromEntries(items.map(x=>[x.muscle,x])),[items]);
 return <View style={styles.wrap}><View style={styles.segment}>{(['front','back'] as Side[]).map(s=><Pressable key={s} onPress={()=>setSide(s)} style={[styles.segmentItem,side===s&&styles.segmentActive]}><Text style={[styles.segmentText,side===s&&styles.segmentTextActive]}>{s==='front'?'Спереди':'Сзади'}</Text></Pressable>)}</View><View style={styles.canvas}><View style={styles.head}/><View style={styles.torso}/><View style={[styles.arm,styles.leftArm]}/><View style={[styles.arm,styles.rightArm]}/><View style={[styles.leg,styles.leftLeg]}/><View style={[styles.leg,styles.rightLeg]}/>{points[side].map(p=>{const item=byMuscle[p.muscle] as RecoveryMuscleStatus|undefined;return <View key={p.muscle} style={[styles.hotspot,tone(item?.status),{top:p.top,left:p.left,width:p.width}]}><Text style={styles.hotspotText}>{muscleMeta[p.muscle].short} · {item?.score??'—'}</Text></View>})}</View><View style={styles.legend}><Text style={styles.legendText}>● готова</Text><Text style={styles.legendText}>◐ частично</Text><Text style={styles.legendText}>○ утомлена</Text></View></View>
}
const styles=StyleSheet.create({wrap:{borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:14,gap:10},segment:{flexDirection:'row',borderWidth:1,borderColor:colors.border,borderRadius:12,padding:3},segmentItem:{flex:1,alignItems:'center',paddingVertical:7,borderRadius:9},segmentActive:{backgroundColor:colors.primary},segmentText:{fontWeight:'800',fontSize:12},segmentTextActive:{color:colors.inverse},canvas:{height:430,width:215,alignSelf:'center',position:'relative'},head:{position:'absolute',top:8,left:88,width:40,height:44,borderWidth:2,borderRadius:22,opacity:.18},torso:{position:'absolute',top:61,left:56,width:104,height:178,borderWidth:2,borderRadius:38,opacity:.18},arm:{position:'absolute',top:78,width:30,height:185,borderWidth:2,borderRadius:18,opacity:.18},leftArm:{left:25},rightArm:{right:25},leg:{position:'absolute',top:232,width:40,height:185,borderWidth:2,borderRadius:20,opacity:.18},leftLeg:{left:64},rightLeg:{right:64},hotspot:{position:'absolute',minHeight:31,borderRadius:16,borderWidth:1,alignItems:'center',justifyContent:'center',paddingHorizontal:7},ready:{backgroundColor:'#EAF5EE',borderColor:colors.success},moderate:{backgroundColor:'#F5F1E8',borderColor:'#9A742B'},fatigued:{backgroundColor:'#F7EAEA',borderColor:colors.danger},hotspotText:{fontSize:11,fontWeight:'900'},legend:{flexDirection:'row',justifyContent:'space-between'},legendText:{fontSize:10,color:colors.textMuted,fontWeight:'700'}});
